#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-23 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))
AUTHOR = "GamblingLawyers.com Editorial Team"

ARTICLES = [
{
 "slug": "brazil-online-casino-ban-threat-election-licensed-operator-risk-2026",
 "title": "Brazil's Casino Ban Threat Tests Licensed Firms",
 "category": "Market Entry",
 "excerpt": "Lula has signalled a possible online casino ban days before the election. Licensed operators face a risk they cannot price.",
 "publish_date": "2026-09-23T07:30:00Z",
 "related_jurisdictions": ["brazil", "colombia", "peru"],
 "related_firms": ["pinheiro-neto-advogados", "mattos-filho"],
 "body": [
  "President Luiz Inacio Lula da Silva has said that if the decision were his alone, online betting companies in Brazil would be shut down. He has described a personal disposition to eliminate gambling, has compared betting addiction to crack cocaine in a podcast appearance on 16 September, and has said he met eight victims of online betting before repeating the position on a livestream. Trade reporting indicates the government is weighing a prohibition directed at online casino activity while preserving fixed-odds sports betting, which contributed roughly 8.7 billion reais to public revenue in the first seven months of 2026. General elections fall on 4 October.",
  "Operators and their advisers must separate two questions that the political noise tends to merge. The first is whether a ban is likely. The second is what legal instrument could deliver one, and on what timetable. Those are different enquiries with different answers, and the second is the one that determines whether a licensed operator should be changing anything this month. A presidential preference expressed on a livestream is not a legal act, and Brazil's regulatory architecture for betting was constructed by statute and implemented through an extensive body of secretariat ordinances. Unwinding the online casino component of that architecture is not a matter of executive fiat.",
  "The distinction between sports betting and online casino is the feature of the reported proposal that carries the most legal weight. Brazil's licensed operators paid substantial authorisation fees for a licence that covers both verticals, built their commercial models on the revenue mix that combination produces, and did so in reliance on a regime the state itself designed and administered. A measure that removes one vertical from an existing authorisation, mid-term, engages the protection of the acquired right and the constitutional guarantees around legal certainty. Counsel at Pinheiro Neto Advogados and Mattos Filho have been flagging that a prohibition drafted without a transition mechanism and without compensation would attract immediate constitutional challenge, and that the prospect of that challenge is itself a constraint on how any measure is drafted.",
  "There is also a separation of powers dimension that determines the form any restriction would take. Congress has repeatedly demonstrated that it holds its own view of gambling policy, and the legislative record includes both restrictive proposals and measures that expanded the regulated perimeter. A prohibition introduced by provisional measure would take immediate effect but would lapse unless converted by Congress within the constitutional period, which creates the worst possible outcome for operators: a shutdown that might be reversed after the commercial damage is done. A prohibition introduced by ordinary bill would proceed at legislative speed and would be exposed to the full range of amendments. Neither route is quick, and both are visible in advance.",
  "For operators, the practical response is scenario planning rather than exit. The scenarios worth modelling are a full online casino prohibition with a transition period, a prohibition without transition, a substantial tightening of casino product rules short of prohibition, and a further advertising restriction that leaves the product lawful but materially harder to market. Each has a different effect on the value of a Brazilian licence and on the covenants in any financing attached to it. Operators with debt facilities containing material adverse change or regulatory event clauses should read those clauses now, because the trigger language in a facility drafted in 2024 may not have contemplated a partial vertical prohibition.",
  "Transaction activity in the Brazilian market will feel this first. An acquirer pricing a licensed Brazilian operator is pricing a revenue stream of which online casino is typically the larger and higher margin part, and the reported proposal converts that part into a contingent asset. The predictable response is a shift from fixed consideration to earn-out structures tied to the survival of the casino vertical, together with specific warranty and indemnity coverage. Sellers should expect diligence requests directed at the revenue split by vertical, at the transferability of the authorisation, and at whether the target has any exposure to the advertising practices that have attracted the sharpest political criticism.",
  "The regional consequence is that Brazil ceases, for the moment, to be the template. Colombia and Peru have both been cited as evidence that Latin American regulation stabilises after an initial adjustment period, and Brazilian developments were expected to reinforce that. A prohibition, or even a sustained threat of one, tells prospective entrants elsewhere in the region that a licensed and taxed market can become a political target once its social visibility exceeds its fiscal contribution. Operators building regional portfolios should weight that lesson into their assumptions about jurisdictions where regulation is new and the political consensus behind it is shallow.",
  "The advice for licensed operators through to the election is to do nothing irreversible and everything documentary. Maintain full compliance with the existing regime, because an operator that has been conspicuously compliant is a poor example for a government seeking to justify prohibition. Compile the evidence of tax contribution, employment and responsible gambling investment that will be relevant if a transition period is negotiated. Review the terms on which customer balances are held, since any prohibition will require an orderly return of funds and the operators that have planned that process will be distinguished from those that have not. And treat the period after 4 October, rather than the period before it, as the point at which the legal position becomes capable of assessment."
 ]
},
{
 "slug": "ukgc-targetlocal-remote-licence-suspension-aml-section-116-2026",
 "title": "Remote Licence Suspended, Betting Shops Stay Open",
 "category": "Enforcement",
 "excerpt": "The Commission suspended one operator's remote licence over AML concerns while leaving its retail permission intact. The split matters.",
 "publish_date": "2026-09-23T08:15:00Z",
 "related_jurisdictions": ["united-kingdom", "gibraltar", "malta"],
 "related_firms": ["harris-hagan", "wiggin-llp", "joelson-llp", "northridge-law-llp", "mishcon-de-reya-llp"],
 "body": [
  "The Gambling Commission suspended the combined remote operating licence of Targetlocal Ltd, which trades as Ken Howell's Sports Betting and operates kenhowells.com, with immediate effect on 21 September 2026. The suspension followed enquiries that the Commission says revealed anti-money laundering failings, and it sits alongside a regulatory review opened under section 116 of the Gambling Act 2005. Customers retain access to their accounts and may withdraw funds. The company's non-remote general betting standard licence is unaffected, so the retail business continues to trade while the online business does not.",
  "That split is the feature of the action that licensees should study, because it demonstrates the granularity available to the Commission when it decides what to suspend. Section 118 permits suspension of an operating licence pending review, and where an operator holds separate remote and non-remote permissions the regulator can act against one and leave the other running. The proportionality analysis behind that choice is straightforward: the conduct identified was located in the remote business, the remote business presents the money laundering risk profile the Commission was concerned about, and suspending the retail permission would have caused harm to employees and customers without addressing the risk. Operators with multi-licence structures should understand that this granularity cuts both ways and does not insulate a group from action against the whole.",
  "The commercial effect of a remote suspension is nevertheless severe and immediate in a way that a financial penalty is not. The operator must cease taking online bets while continuing to service withdrawals, which means the business runs a negative cash position for the duration. Payment providers, platform suppliers and affiliates will review their arrangements within days, and some will suspend rather than wait for the outcome. Practitioners at Harris Hagan, Wiggin LLP, Joelson LLP, Northridge Law LLP and Mishcon de Reya LLP have long observed that a suspension frequently determines the commercial outcome before the regulatory review reaches any conclusion, because the operator's counterparty relationships do not survive the pause even where the licence ultimately does.",
  "The AML fact pattern behind suspensions of this kind is familiar and largely independent of operator size. The recurring elements are a risk assessment that does not reflect the actual customer base, policies and procedures that were adopted from a template and never calibrated, enhanced due diligence triggers set at thresholds that almost no customer reaches, and source of funds enquiries that accept assertion in place of evidence. None of those failures requires bad faith. They are the predictable result of a small compliance function running controls designed for a smaller business than the one that grew around them, and the Commission has made clear in successive public statements that scale is not a defence.",
  "Smaller operators should read this action as confirmation that the regulatory expectation does not scale down. The Commission's published money laundering and terrorist financing risk assessment applies to every licensee, and the obligation to keep a business risk assessment current and to tailor policies to it is not moderated by turnover. An operator with a handful of compliance staff must still be able to demonstrate that it identified its own risks, that its controls address those risks specifically, and that it monitored whether the controls worked. What smaller operators frequently lack is the second line function that would test the first, and the absence of any independent challenge is often the finding that converts a set of weaknesses into a suspension.",
  "The section 116 review that follows a suspension is a broader process than the conduct that triggered it. A review examines whether the licensee remains suitable to hold a licence, which imports the suitability of those who control it, the adequacy of its governance, and its financial position as well as the specific failures identified. Licensees under review frequently underestimate how far the enquiry can travel from its starting point. The practical implication is that the response to a suspension should be a comprehensive remediation programme with independent verification, rather than a narrowly drawn rebuttal of the particular allegations, because the regulator's question at the end is not whether the original finding was correct but whether the business is now compliant.",
  "There is a sector context that gives this action a significance beyond the operator concerned. British online gambling has been consolidating, and the compliance cost of holding a remote licence has risen faster than the revenue available to smaller licensees. Deposit limit requirements, financial risk assessments, product design standards and AML supervision each impose fixed costs that a large operator amortises across a substantial customer base and a small one does not. A suspension of this kind accelerates a process already under way, and the realistic outcome for many smaller remote licensees is sale, surrender or a retreat to retail rather than remediation.",
  "For licensees generally, the immediate exercise is to test the assumptions in their own AML framework against the pattern above. Confirm that the business risk assessment has been reviewed since the last material change to the customer base or product set. Identify how many customers triggered enhanced due diligence in the last twelve months and ask whether that number is credible. Establish whether source of funds documentation is verified or merely collected. And confirm that someone independent of the compliance function has tested the controls and recorded the result, because the licensee that can produce that record occupies a materially stronger position at the point the Commission asks."
 ]
},
{
 "slug": "uk-dcms-unlicensed-gambling-sponsorship-ban-consultation-2027",
 "title": "UK Moves to Ban Unlicensed Gambling Sponsorship",
 "category": "Compliance",
 "excerpt": "DCMS wants unlicensed sponsorship gone before the 2027/28 season. The white label carve-out will decide how much changes.",
 "publish_date": "2026-09-23T09:00:00Z",
 "related_jurisdictions": ["united-kingdom", "curacao", "ireland"],
 "related_firms": ["harris-hagan", "wiggin-llp", "mishcon-de-reya-llp", "northridge-law-llp"],
 "body": [
  "The Department for Culture, Media and Sport's consultation on banning sponsorship and physical advertising by gambling operators that do not hold a Gambling Commission licence closed on 9 September 2026, and the government has indicated an intention to introduce the ban during August 2027, ahead of the 2027/28 football season. The scope extends beyond sport to cultural events and music venues, on the stated basis that a sport-only prohibition would simply relocate the activity. Government estimates cited in the consultation indicated that around forty percent of Premier League clubs held sponsorship or advertising arrangements with unlicensed operators during the 2025/26 season.",
  "The measure is unusual in British gambling policy because it is directed at operators the Commission cannot license and does not supervise. The regulatory problem it addresses is that an operator based offshore, serving markets in Asia or Latin America and holding no British permission, can nevertheless purchase the most valuable advertising inventory in British sport. The Commission's existing powers reach licensees and, in limited circumstances, those who advertise unlawful gambling to British consumers, but they do not straightforwardly reach a sponsorship arrangement between a foreign operator and a British club where the operator does not transact with British customers. Legislating against the arrangement itself, and placing the obligation on the British counterparty, is the response to that gap.",
  "That places the compliance burden on clubs, venues and rights holders rather than on operators, which is the structural point advisers should be making to sporting clients now. A club entering a sponsorship agreement will need to verify the licensing status of the counterparty, to maintain that verification through the term, and to hold a termination right exercisable if the status changes. None of that is difficult in principle. It is difficult in practice because sponsorship counterparties are frequently intermediaries, marketing agencies or group companies whose relationship to the operating entity is not disclosed in the contract, and because the entity named on a shirt is not always the entity holding a licence or lacking one.",
  "The white label question is where the substance of the measure will be decided, and reporting suggests that white label services are not caught. A white label arrangement places an unlicensed brand on a licensed operator's platform, with the licensed operator holding the permission and bearing regulatory responsibility while the brand supplies the marketing. If a brand operating under a British white label can continue to sponsor, the visible effect of the ban is smaller than its framing suggests, and the predictable market response is a migration of sponsorship arrangements into white label structures. Practitioners at Harris Hagan, Wiggin LLP, Mishcon de Reya LLP and Northridge Law LLP have consistently identified white label supervision as the weak point in the British advertising perimeter, and a carve-out here would confirm the point.",
  "Entain's renewed call for an immediate prohibition, made after the consultation closed, illustrates why licensed operators support a measure that restricts advertising. The competitive complaint is that licensed operators bear the full cost of British compliance, including deposit limits, financial risk assessments, advertising codes and the statutory levy, while competing for the same audience attention with operators that bear none of it. From that perspective the ban is not a restriction on gambling advertising but a correction of an asymmetry, and the argument has the advantage of being made by the businesses that would normally resist advertising restrictions.",
  "The enforcement design is the part of the proposal that will determine whether it works, and it is the part the consultation response most needs to resolve. A prohibition enforced against clubs through a licensing or sanctioning mechanism that governing bodies administer will move quickly and will be applied unevenly. A prohibition enforced through a statutory penalty regime will move slowly and will require an enforcement authority with the resources to investigate corporate structures deliberately built to obscure ownership. Whichever route is chosen, the offence will need to be defined by reference to conduct the British party can reasonably ascertain, because an obligation to know facts that the counterparty controls and conceals is not an obligation that can be complied with in good faith.",
  "There is a jurisdictional dimension that follows the operators rather than the clubs. A substantial share of the sponsorship arrangements at issue involve operators holding Curacao permissions, and Curacao's own reforms have shifted territorial accountability onto licensees in a way that makes a British sponsorship a harder fact for a licensee to explain to its own regulator. An operator that sponsors a Premier League club while holding no British licence is making a public statement about the markets it serves, and that statement is available to every regulator that supervises it. The British measure therefore has the potential to generate consequences in the operator's home jurisdiction that the British authorities do not have to impose themselves.",
  "For clients on the sporting side, the work to do before August 2027 is contractual and begins with the existing book. Identify every gambling sponsorship arrangement currently in place, establish which legal entity is the counterparty and whether it holds a British licence, and determine the expiry date and the termination rights. Where an arrangement extends beyond the anticipated commencement, negotiate a regulatory termination right now rather than after the legislation is laid, because the commercial leverage is better before the counterparty knows the deal is unlawful. And build licensing verification into the standard onboarding process for new commercial partners, since the cost of that process is trivial compared with the cost of unwinding a shirt deal mid-season."
 ]
},
{
 "slug": "italy-adm-aml-concession-termination-nine-year-terms-2026",
 "title": "AML Failure Can Now Cost an Italian Concession",
 "category": "Licensing",
 "excerpt": "Italy has written anti-money laundering compliance into concession terms, making breach a termination risk rather than a fine.",
 "publish_date": "2026-09-23T09:45:00Z",
 "related_jurisdictions": ["italy", "malta", "spain"],
 "related_firms": ["dla-piper-italy", "cms-italy", "norton-rose-fulbright-italy", "studio-legale-sbordoni-and-partners"],
 "body": [
  "Italy's reorganised online concession framework has embedded anti-money laundering compliance directly into the terms of the concession itself, with the consequence that a failure to meet AML standards can engage termination of a nine-year authorisation rather than a financial penalty applied alongside it. That is a structural change to the risk profile of the Italian market, and it is one that operators accustomed to treating AML as a supervisory matter handled by the financial intelligence authority have not uniformly absorbed. A condition of concession is enforced by the awarding administration through contractual mechanics, and those mechanics are faster and less forgiving than an administrative sanctions process.",
  "The distinction matters because of what an operator has paid for. The concession fee for an Italian online authorisation is substantial, the term is nine years, and the commercial model that justifies the fee depends on holding the concession for most of that term. Converting AML compliance from a regulatory obligation into a condition of an asset with that profile changes the calculation an operator should be performing when it decides how much to invest in controls. The relevant comparison is no longer between the cost of compliance and the expected penalty. It is between the cost of compliance and the value of the concession, and that comparison produces a different answer.",
  "Italian AML obligations for gambling operators derive from the national implementation of the European framework and include customer due diligence at defined thresholds, the identification of beneficial owners, the retention of records, and the reporting of suspicious transactions to the Unita di Informazione Finanziaria. Where those obligations become concession conditions, a shortfall generates two exposures simultaneously: the ordinary consequence under the AML regime, and a breach of the concession that the awarding administration may act upon. Counsel at DLA Piper Italy, CMS Italy, Norton Rose Fulbright Italy and Studio Legale Sbordoni & Partners have been advising concession holders and applicants that the two tracks must be managed together, because a remediation plan agreed with one authority does not resolve the position with the other.",
  "For operators whose Italian activity sits within a wider European group, the practical difficulty is that group AML functions are typically designed around a lead jurisdiction. A group headquartered in Malta will commonly run a single financial crime framework calibrated to Maltese requirements, with local variations applied as overlays. That structure is efficient and it is also the reason Italian specific obligations are the ones most often missed, because an overlay depends on someone having identified the difference in the first place. The threshold at which due diligence is triggered, the form in which records must be held, and the domestic reporting route are all points at which Italian requirements diverge, and each is capable of producing a finding.",
  "Applicants in the current concession process face a further question, which is whether their historic AML record is a matter the awarding administration will examine. Suitability assessments in the Italian process examine the applicant, its corporate group and the individuals who control it, and a documented AML failure in another European jurisdiction is a fact that falls within that assessment. Applicants should assume it will be found rather than hope it will not, and should prepare a narrative that explains what happened, what was remediated and what independent verification confirms the remediation. An applicant that discloses and explains is in a materially better position than one whose regulatory history is discovered during evaluation.",
  "The termination risk also reshapes transaction structuring in the Italian market. An acquirer buying an Italian concession holder is buying an asset whose continued existence is conditional on the target's compliance, and ordinary warranty protection is a poor substitute for the asset itself. The response is deeper pre-signing diligence directed specifically at AML controls, including sample testing of customer files rather than reliance on policy documents, together with conditions precedent requiring remediation of identified gaps before completion. Where the asset cannot be re-acquired if lost, the usual allocation of risk through indemnities does not deliver the buyer what it is paying for.",
  "There is a comparative point that concession holders should register. Spain has been tightening the financial conditions attached to its licences, and Malta has focused its supervisory agenda on financial crime risk within its licensee base. The direction across southern Europe is the same: AML performance is becoming a condition of continued market access rather than a matter resolved by payment. Operators holding permissions in more than one of these jurisdictions should expect that a finding in one will be considered in the others, and should assume that supervisory cooperation between European regulators on financial crime is now routine rather than exceptional.",
  "The preparatory work for concession holders is specific and testable. Confirm that the Italian AML framework is a document written for Italy rather than a translated group policy. Establish that customer due diligence triggers reflect Italian thresholds and that the evidence collected satisfies Italian verification standards. Confirm that suspicious transaction reporting runs through the correct domestic channel and that the volume of reports is consistent with the size of the customer base. And commission an independent review whose output can be handed to the awarding administration, because in a regime where breach threatens the concession, the ability to demonstrate assurance is worth more than the ability to argue about a finding."
 ]
},
{
 "slug": "uk-gambling-yield-17-5bn-industry-statistics-budget-tax-2026",
 "title": "£17.5bn Yield Arrives Before a Gambling Tax Budget",
 "category": "Tax",
 "excerpt": "Record British gambling yield gives the Treasury a number to tax, and gives retail betting a decline it must now defend.",
 "publish_date": "2026-09-23T10:30:00Z",
 "related_jurisdictions": ["united-kingdom", "ireland", "gibraltar"],
 "related_firms": ["pinsent-masons-llp", "joelson-llp", "harris-hagan", "wiggin-llp"],
 "body": [
  "The Gambling Commission's industry statistics for the financial year April 2025 to March 2026, published on 17 September, record a total gross gambling yield of 17.5 billion pounds, an increase of 4.4 percent on the previous year and the fifth consecutive year of growth. Excluding lotteries, yield was 13.2 billion pounds, up 4.7 percent. The remote casino, betting and bingo sector produced 8.3 billion pounds, up 6.9 percent. Licensed premises fell to 8,081, down two percent, with betting shops down 3.6 percent to 5,617. The figures arrive as the Treasury prepares a Budget in which gambling taxation is widely expected to feature.",
  "The political arithmetic those numbers produce is uncomfortable for the industry. A sector reporting record yield in a year of constrained public finances presents as a source of revenue rather than as a business under pressure, and the divergence between the remote and retail lines makes the point sharper. Remote yield grew at nearly seven percent while the premises estate contracted. A Treasury looking for a base to tax will see growth concentrated in the channel that is cheapest to serve and least dependent on physical presence, and will draw the obvious conclusion about where an increase can be absorbed.",
  "The specific proposal that has occupied the industry is the harmonisation of the duties applied to different gambling products, which in practice means raising remote gaming duty toward or beyond the rates applied elsewhere and reconsidering machine games duty. Betfred's founder has warned publicly that an increase in machine games duty could put retail betting out of business by 2030, and the warning has more force than such statements usually carry because the premises numbers in the Commission's own data are already falling. The difficulty for the industry is that the same dataset supports both arguments: it shows a shrinking retail estate and it shows a growing total.",
  "Operators should be modelling the interaction between a duty increase and the existing compliance cost base rather than the duty increase alone. British remote operators already carry the cost of deposit limit functionality, financial risk assessments, product design standards, the statutory levy and an AML supervisory burden that has grown steadily. Each of those reduces the margin available to absorb a tax increase, and the cumulative effect is that a rate rise which appeared tolerable against 2021 margins may not be tolerable against 2026 margins. Advisers at Pinsent Masons LLP, Joelson LLP, Harris Hagan and Wiggin LLP have been encouraging clients to present that cumulative position with evidence, because a submission that quantifies the stack is more persuasive than one that asserts pressure.",
  "The channelisation argument will be deployed and should be deployed carefully. The proposition that higher duty pushes customers toward unlicensed supply is supported by experience in the Netherlands, where a rate increase to 37.8 percent produced revenue below projection alongside operator exits, and it is contested in Britain by those who regard black market estimates as industry advocacy. The credibility of the argument in the Budget process depends entirely on the quality of the evidence behind it. Operators that can demonstrate observed customer migration with transaction level data will be heard. Operators that offer a commissioned survey will not, and the repeated use of contested figures has cost the industry credibility it now needs.",
  "Retail operators have a different and in some ways stronger case, which is that the premises estate is an employment and high street question as well as a fiscal one. A betting shop is a lease, a set of jobs and a business rates liability, and a duty increase that closes shops produces offsetting revenue losses that a static scoring model will not capture. The Commission's data quantifies the contraction already occurring without any increase, which gives the argument a factual foundation that does not depend on the operator's own projections. The parallel with Ireland, where a betting duty increase has raised the same concern about retail viability, is close enough to be instructive on both sides.",
  "There is a contractual dimension that operators should address before rather than after any announcement. Supplier agreements, content licensing arrangements and revenue share structures typically define the revenue base by reference to net gaming revenue, and the treatment of duty within that definition determines who bears an increase. Where the definition is unclear, a rate rise falls in a place neither party intended. Machine supply agreements in retail present the same issue in a more acute form, because the commercial terms are frequently fixed for a period that will span any change and the operator carries the whole of the margin compression.",
  "The practical preparation is the same whether or not an increase materialises. Model the effect of a range of rates on each product line separately, since a harmonisation measure will not affect remote casino, remote betting and machines equally. Identify the contracts in which the incidence of a duty change is ambiguous and seek clarification while the question is hypothetical. Assemble the evidence on compliance cost, employment and customer behaviour that a submission or a post-announcement representation would require. And plan on the basis that the 17.5 billion pound figure will be quoted in the Budget debate regardless of what the industry says about it, because it is the only number in the discussion that carries the regulator's authority."
 ]
},
]


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,'
        'author:"%s",author_slug:"",publish_date:%s,'
        'related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]),
            esc(a["title"]),
            esc(a["category"]),
            esc(a["excerpt"]),
            AUTHOR,
            esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_23sep.bak")
        patch(p)
    print("done")
