#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-06 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))

ARTICLES = [
{
 "slug": "colorado-fanatics-self-exclusion-marketing-fine-vip-controls",
 "title": "Colorado fine puts VIP teams inside the exclusion perimeter",
 "category": "Enforcement",
 "excerpt": "A $20,000 Colorado settlement over two promotional texts to a self-excluded customer shows how narrowly regulators read marketing suppression.",
 "publish_date": "2026-09-06T07:30:00Z",
 "related_jurisdictions": ["united-states"],
 "related_firms": ["ifrah-law-pllc", "zwillgen-pllc", "fox-rothschild-llp", "dickinson-wright-pllc"],
 "body": [
  "The Colorado Division of Gaming has settled with Fanatics Sportsbook over two promotional messages sent to a customer who had placed himself on the state's self-exclusion list. The sum, $20,000, is trivial against the operator's revenue and has been read in some quarters as a signal that the Division treats the conduct as minor. That reading misunderstands what the settlement establishes. The customer self-excluded on 15 January 2026. A member of the operator's VIP team sent a promotional offer on 1 February and a second on 17 February. At no point could the customer have placed a bet, because the exclusion blocked account access throughout. The violation was complete on transmission of the message, without any wagering, any loss and any complaint of harm.",
  "That is the legally significant feature. Self-exclusion obligations in most US jurisdictions operate on two distinct limbs: a prohibition on accepting wagers from an excluded person, and a separate prohibition on directing gambling-related marketing to that person. Operators build their controls almost entirely around the first limb, because the wagering block is a systems problem with a systems answer, and because a wager taken from an excluded customer is visible in the transaction record. The marketing limb is a data governance problem, and it fails silently. Nobody notices that a suppression flag did not propagate to a customer relationship platform until a regulator, or the excluded person, notices for them.",
  "The channel through which the failure occurred is the part operators should study. This was not a bulk email campaign misfiring against a stale list. It was a VIP account manager contacting a high value customer individually. VIP and player development teams work from relationship management tools, personal contact lists and, in practice, from memory and personal rapport built over months. They frequently sit outside the marketing technology stack that receives the nightly exclusion feed, and they operate under commercial incentives that reward reactivation of lapsed high value accounts. A customer who has just stopped playing is precisely the profile a VIP manager is compensated to re-engage, and self-exclusion presents to that manager as a customer who has gone quiet.",
  "US gaming regulatory counsel, including Ifrah Law PLLC, ZwillGen PLLC, Fox Rothschild LLP and Dickinson Wright PLLC, have consistently advised that the marketing suppression obligation should be engineered as a hard block at the point of send rather than as a list hygiene process. The distinction matters because list hygiene assumes every outbound message originates from a system that consumes the suppression list. Once an account manager can send a message from a device or a tool that never queries the exclusion register, no amount of list accuracy prevents the breach. The control that works is one that intercepts the message, whatever its origin, and checks the recipient against the register before delivery.",
  "The remediation terms are more onerous than the penalty and are the real cost of the settlement. Fanatics agreed to audit its own self-exclusion population to determine whether any other excluded customer was contacted in the same way between 1 January 2024 and 1 March 2026, and to report the findings to the Division in detail. A twenty six month look back across every outbound communication channel is a substantial forensic exercise, and it is one whose results the operator must hand to the regulator without knowing in advance what they will show. Operators negotiating settlements should price the look back rather than the fine, and should understand that a look back producing further breaches will be assessed against an operator that has already admitted the underlying control failure.",
  "The company self-reported the infraction, and the Division's order reflects that in the outcome. Self-reporting has become the single largest determinant of penalty in US state gaming enforcement, more so than the gravity of the conduct in many cases, and the settlement is consistent with that pattern. The corollary is uncomfortable for operators who discover historic breaches during an internal review. Once the review has identified a marketing contact with an excluded customer, the choice is between disclosing a breach that will attract a modest penalty and a supervised remediation, or holding it and risking discovery by a regulator that will treat the non-disclosure as the more serious matter.",
  "There is a multistate dimension that a single Colorado order does not capture. Operators licensed across twenty or more jurisdictions maintain separate exclusion registers with different scopes, different durations, different reinstatement mechanics and different rules on what marketing suppression covers. A customer excluded in Colorado is not necessarily excluded in a neighbouring state, and a national marketing campaign has to reconcile all of them at once. The architecture that survives this is a single canonical suppression service that every outbound channel must call, with state-level rules applied within it, rather than per-state lists distributed to per-channel systems that then drift apart.",
  "The lesson generalises well beyond Colorado. Regulators have shifted from asking whether an operator has a self-exclusion programme to asking whether the programme holds against the operator's own commercial incentives. A settlement that costs $20,000 and requires a two year audit is not a regulator treating the conduct lightly. It is a regulator establishing, at low cost to the licensee, that the exclusion perimeter includes the people whose job is to bring customers back."
 ]
},
{
 "slug": "uk-illegal-social-media-lotteries-raffles-licensing-boundary",
 "title": "Social media raffles test the UK lottery licensing line",
 "category": "Licensing",
 "excerpt": "The Commission logged 438 suspected illegal lotteries and stopped 356 draws, exposing how few promoters understand the free draw exemption.",
 "publish_date": "2026-09-06T08:15:00Z",
 "related_jurisdictions": ["united-kingdom"],
 "related_firms": ["harris-hagan", "wiggin-llp", "joelson-llp", "northridge-law-llp"],
 "body": [
  "The Gambling Commission's latest intelligence on social media promotions describes a market that has grown faster than any part of the licensed sector and sits almost entirely outside it. The regulator recorded over 438 suspected illegal lotteries in 2025 and a further 544 reports of society lotteries presenting themselves as free draws or prize competitions. It halted 356 illegal draws during the year and disrupted a further 79 in early 2026, issued 741 cease and desist notices, and referred more than 397,000 URLs to search engines for removal. Reports of suspected illegal draws on TikTok rose year on year. Almost none of the promoters involved would describe themselves as gambling operators.",
  "The legal architecture they are falling foul of is deceptively simple and widely misread. Under the Gambling Act 2005 a lottery arises where persons pay to enter, one or more prizes are allocated, and the allocation relies wholly on chance. Promoting a lottery without a licence or an applicable exemption is a criminal offence under section 258. The Act carves out two escape routes that promoters reach for instinctively: the free draw, where there is a genuinely free method of entry, and the prize competition, where success depends to a material degree on the exercise of skill, judgement or knowledge. Both routes are narrower than the marketing material that invokes them.",
  "The free draw exemption in Schedule 2 fails most often on the quality of the free entry route rather than its existence. The alternative must be genuinely free, must be as convenient and as well publicised as the paid route, and must offer the same chance of winning. A postal entry buried in terms and conditions, requiring the entrant to hand write details and post them at their own cost while paid entrants click a button, does not meet the standard. Nor does a route that awards paid entrants multiple tickets and free entrants one. Promoters routinely construct free entry mechanisms designed to be technically present and practically unused, which is the precise configuration the exemption was drafted to defeat.",
  "The prize competition route fails on the calibration of the skill element. The statutory test asks whether the requirement to exercise skill, judgement or knowledge would be likely to prevent a significant proportion of persons who wish to participate from doing so, or would be likely to prevent a significant proportion of those who do participate from receiving a prize. A tie-break question that any entrant can answer by searching the internet on the same screen satisfies neither limb. A question that eliminates nobody eliminates the exemption. Promoters who add a question to a raffle in the belief that any question suffices are, in law, running an unlicensed lottery with an extra step.",
  "British gambling counsel, including Harris Hagan, Wiggin LLP, Joelson LLP and Northridge Law LLP, have long advised that the analysis has to be run on the mechanic as it actually operates rather than on the mechanic as drafted. That is where the social media context bites hardest. A promotion may be structured lawfully and then be executed unlawfully by the promoter's own posts: a live video that tells viewers to send payment by bank transfer, a comment thread in which the free entry route is never mentioned, a story that closes entries early for anyone who has not paid. On a platform where the promotion is the stream of content, the terms and conditions are not the promotion.",
  "The Commission's finding on consumer attitudes is the part with the greatest practical consequence. Participants care whether a draw appears genuine, meaning whether a real prize will be delivered by a real person, and give little thought to whether the draw is lawfully operated. That is rational from the participant's perspective and disastrous from a consumer protection one, because it means the market provides no corrective pressure. An unlicensed promoter who pays out reliably acquires exactly the reputation that attracts more entrants, while carrying none of the obligations on fund protection, age verification, or the proportion of proceeds returned to good causes that a licensed society lottery must satisfy.",
  "That asymmetry is now the licensed sector's problem as much as the regulator's. Society lotteries operate under prescribed limits on proceeds and prizes, a minimum contribution to good causes, and full licensing and reporting obligations, and they have been arguing for reform of those limits as the sector approaches a billion pounds in gross gambling yield. They are competing for the same consumer against promoters carrying no compliance cost at all. Any argument for relaxing the statutory limits will be tested against the regulator's view that the immediate problem is not the constraints on licensed operators but the volume of activity outside the perimeter entirely.",
  "For anyone running promotional draws, including brands and charities with no gambling ambitions whatever, the practical position is that the offence does not require intent and the enforcement is now systematic. Promoters should document the free entry route and test whether a real entrant could use it as easily as the paid route, apply the statutory skill test to the actual question rather than to the concept of a question, and treat every live post as part of the promotion for regulatory purposes. Those who cannot satisfy the exemptions should consider whether the activity is one that requires a licence, because the Commission has demonstrated that it can identify hundreds of these promotions a year and is willing to stop them."
 ]
},
{
 "slug": "ireland-grai-advertising-certification-deadline-affiliates-2026",
 "title": "Ireland's ad certification deadline catches the supply chain",
 "category": "Compliance",
 "excerpt": "Advertisers had until 1 September to recertify against GRAI licences. Those who missed it lose certification and, with it, paid distribution.",
 "publish_date": "2026-09-06T09:00:00Z",
 "related_jurisdictions": ["ireland", "united-kingdom", "malta"],
 "related_firms": ["mishcon-de-reya-llp", "pinsent-masons-llp", "bird-and-bird", "cms"],
 "body": [
  "The 1 September 2026 deadline for advertisers to complete recertification against licences issued by the Gambling Regulatory Authority of Ireland has now passed, and its effects are being felt at a layer of the market that regulatory analysis usually ignores. The certification in question is not a licence. It is the permission that advertising platforms require before they will accept gambling advertising for an Irish audience, and it is granted on proof that the advertiser holds, or is authorised to promote on behalf of, an entity licensed by the GRAI. Advertisers who did not complete the reapplication lose their certification, and the practical consequence of losing certification is the loss of paid distribution.",
  "This is a familiar mechanism operating in a new statutory setting. The Gambling Regulation Act 2024 created a licensing regime administered by the GRAI, which became operational in 2025 and has been issuing licences to remote betting and gaming operators through 2026. Platform certification regimes take their reference point from whatever the local regulator recognises, so the arrival of a GRAI licence register displaced the previous evidentiary basis for Irish gambling advertising and forced every certified advertiser to prove its position again against the new register. The deadline was an administrative consequence of the regime going live rather than a regulatory sanction, which is why it caught parties who do not monitor gambling regulation at all.",
  "The exposed population is principally the affiliate and agency layer. A licensed operator with a compliance function tracks its own certification status because paid acquisition is a board level budget line. An affiliate running comparison sites, or a media agency buying on behalf of several operators, may hold certification in its own name and may not have been reading GRAI correspondence addressed to licensees. The result is that a certification lapse can sever an operator's distribution without any failure by the operator, and frequently without the operator's knowledge until performance data shows the traffic gone.",
  "The commercial contracts that govern these relationships are usually silent on the point. Affiliate agreements allocate responsibility for compliance with advertising codes and for the content of marketing material, and they typically require the affiliate to hold all necessary permissions. They rarely specify who monitors platform certification status, who is responsible for renewal, what notice is owed if certification lapses, and what happens to accrued commission during a suspension. Advertising and gambling practices, including Mishcon de Reya LLP, Pinsent Masons LLP, Bird and Bird and CMS, have advised that certification status should be a standing warranty with a positive notification obligation rather than an assumed background condition.",
  "The certification layer also sits alongside substantive Irish restrictions that operate independently of it. The Act imposes a watershed prohibiting gambling advertising on television, radio and on-demand audiovisual media between 5.30am and 9.00pm, prohibits advertising targeted at children, and gives the Authority power to apply to the High Court to restrain contravening advertising, with certain breaches carrying criminal penalties. Certification governs whether an advertiser may buy at all. The watershed and targeting rules govern what may be shown and when. Compliance with one says nothing about compliance with the other, and an advertiser that has recertified successfully has cleared an administrative gate rather than a content review.",
  "For operators, the immediate exercise is a reconciliation rather than a legal analysis. Every entity that places gambling advertising for an Irish audience on the operator's behalf, including affiliates, agencies, influencer intermediaries and any group company running regional campaigns, should be identified and its certification status confirmed directly rather than assumed. Where certification has lapsed, campaigns should be paused before the platform pauses them, because a platform level enforcement action carries account history consequences that a voluntary pause does not.",
  "The structural lesson is that private compliance infrastructure has become a transmission mechanism for public regulation. Advertising platforms operate certification regimes that mirror national licensing registers, and they enforce those regimes with a speed and a bluntness no regulator can match. A platform does not conduct a proportionality assessment, does not offer a hearing, and does not distinguish between a deliberate breach and an unopened email. Where a national regulator's register is the input to that machinery, the effective sanction for an administrative lapse is delivered by a commercial intermediary within days.",
  "Ireland will not be the last jurisdiction to produce this pattern. Every newly operational gambling regulator creates a register, every register becomes the reference point for platform certification, and every transition to a new register generates a recertification deadline that falls on parties several steps removed from the licensing process. Operators building compliance calendars for new markets should record the platform recertification dates alongside the statutory ones, and should treat the distribution layer as part of the regulatory perimeter rather than as a procurement matter."
 ]
},
{
 "slug": "portugal-srij-article-21b-advertising-self-exclusion-2026",
 "title": "Portugal weighs an advertising near-ban as SRIJ centralises",
 "category": "Regulatory",
 "excerpt": "A proposed Article 21-B would push Portugal toward a Belgian-style advertising ban, while a national self-exclusion portal reshapes operator duties.",
 "publish_date": "2026-09-06T09:45:00Z",
 "related_jurisdictions": ["portugal", "spain", "belgium", "italy"],
 "related_firms": ["cms", "bird-and-bird", "pinsent-masons-llp", "greenberg-traurig-llp"],
 "body": [
  "Portugal has spent 2026 moving on two fronts at once, and operators focused on the more visible of them are underestimating the other. The visible front is advertising, where amendments to Article 21 of the Advertising Code have already tightened the position and a proposed Article 21-B would take Portugal close to the near-total prohibition Belgium adopted by royal decree. The less visible front is the centralised self-exclusion portal that the Serviço de Regulação e Inspeção de Jogos launched on 8 April 2026, which changes the operational architecture of player protection in a way that will outlast whatever happens to the advertising bill.",
  "The advertising proposal deserves to be assessed on the Belgian precedent rather than on its own drafting. Belgium's near-total ban has been in force long enough to generate evidence, and the evidence is contested. Prohibiting advertising by licensed operators does not remove demand, and where the unlicensed channel is reachable it captures a share of the demand that licensed brands can no longer address. The counterargument, which regulators across Europe have found persuasive, is that advertising volume itself drives participation and harm, and that a reduction in overall participation is the point rather than a side effect. Which of these is correct is an empirical question that Portugal's parliament will resolve by legislating rather than by measuring.",
  "There is a European law dimension that a near-ban engages directly. Restrictions on gambling advertising restrict the freedom to provide services under Article 56 of the Treaty on the Functioning of the European Union, and are permissible where justified by overriding reasons in the public interest, suitable to achieve the objective pursued, applied consistently and systematically, and no more restrictive than necessary. The consistency limb is where advertising bans are most vulnerable. A prohibition that binds private licensed operators while leaving state controlled lottery products free to advertise invites the argument that the measure pursues a commercial objective under a public health justification. Portugal's structure, in which Santa Casa da Misericórdia holds a distinct position, makes that argument available to any operator willing to run it.",
  "The self-exclusion portal is the change with immediate operational consequences. A centralised national register replaces per-operator exclusion with a single act by the player that binds every licensed operator simultaneously, and it shifts the compliance burden from recording exclusions to consuming a register in real time. The obligations that follow are the ones that generate enforcement elsewhere in Europe: checking the register at registration and at every login rather than at account opening alone, suppressing all marketing to registered persons across every channel, and handling the reinstatement process on the register's terms rather than the operator's. Sweden, the Netherlands and Ontario have each produced enforcement activity on precisely these points.",
  "European gambling and advertising practices, including CMS, Bird and Bird, Pinsent Masons LLP and Greenberg Traurig LLP, have observed that operators consistently treat centralised exclusion as a data feed integration and underinvest in the marketing suppression side. The registration and login checks are systems work with a definite completion point. Marketing suppression touches every outbound channel the business operates, including the ones marketing does not control, and it has no completion point because new channels are added continuously. Colorado's recent action against a sportsbook for two promotional messages sent by an account manager to a self-excluded customer illustrates how small the failure can be and how visible it becomes.",
  "The fiscal position sits underneath both developments and shapes how much either matters commercially. Portugal taxes online games of chance at 25% of gross gaming revenue and fixed-odds sports betting on turnover at 8%, a structure that penalises high volume low margin betting products far more heavily than a gross revenue basis would. Combine turnover taxation with an advertising near-ban and the Portuguese sports betting proposition becomes difficult to justify for any operator that is not already established there, because the two measures compress margin and restrict acquisition at the same time. IEJO collections of roughly 164 million euros across the first half of 2025 indicate a market worth defending, but the incremental economics of entering it change materially.",
  "The licensing structure adds a further layer for anyone assessing entry. SRIJ licenses per game type on a three-year renewable basis, and requires financial guarantees of 500,000 euros per licence for player liabilities plus 100,000 euros in respect of the special gambling tax, with payment gateway and data storage infrastructure physically located in Portugal. A three-year term is short relative to the capital required, and the localisation requirement means the technical build cannot be shared with a group platform hosted elsewhere. Those costs are fixed and are incurred before the advertising position is known.",
  "The prudent reading for operators already licensed in Portugal is that the self-exclusion obligations are certain and immediate while the advertising near-ban is contested and uncertain. Compliance effort should be allocated accordingly. Operators should assume the centralised register becomes the reference point for every player protection question SRIJ asks, should build marketing suppression that survives contact from every team including account management, and should keep the Article 21-B debate under review without restructuring their Portuguese business around a bill that has not passed."
 ]
},
{
 "slug": "us-gambling-loss-deduction-90-percent-fair-bet-act-2026",
 "title": "The 90% loss deduction rule reaches US professional bettors",
 "category": "Tax",
 "excerpt": "From 2026 gamblers may deduct only 90% of losses against winnings, creating tax on net-zero years. A repeal bill has stalled in committee.",
 "publish_date": "2026-09-06T10:30:00Z",
 "related_jurisdictions": ["united-states"],
 "related_firms": ["ifrah-law-pllc", "greenberg-traurig-llp", "holland-and-knight-llp", "duane-morris-llp"],
 "body": [
  "The federal tax change that took effect for the 2026 tax year is the most consequential development in US gambling taxation in decades, and it has attracted a fraction of the attention given to state rate rises. Gambling losses are now deductible against gambling winnings only to the extent of 90% of those losses, replacing the long standing rule permitting deduction of losses up to the full amount of winnings. The arithmetic consequence is that a person who wins and loses identical amounts in a year, and is economically flat, has taxable income equal to 10% of their losses. Tax is now payable on a break-even result.",
  "The effect scales with volume rather than with profit, which is what makes it structurally different from a rate increase. A recreational player who wagers modest sums and reports small figures on both sides sees a marginal change. A professional or high volume bettor who cycles millions of dollars through a year, winning slightly more than they lose, can find the disallowed portion of losses exceeding their entire economic gain. At sufficient volume the tax liability exceeds the profit and the activity becomes loss making after tax while remaining profitable before it. There is no rate at which such a person becomes viable again, because the problem is in the base rather than the rate.",
  "The affected population is not confined to individuals who describe themselves as professionals. Advantage players, sports bettors operating across multiple books to capture price differences, poker players with meaningful annual volume and anyone whose activity generates large gross figures on both sides of the ledger face the same arithmetic. The rule does not distinguish between a gambler in the trade or business sense, who reports on Schedule C, and a recreational gambler itemising deductions. Both compute the deduction under the same 90% limitation, and the character of the activity determines other things but not this.",
  "The legislative response has stalled. A House panel declined to advance the FAIR BET Act, which would have restored full deductibility, leaving the change in place for the 2026 year and beyond. The politics of repeal are difficult in a way the drafting is not. The limitation raises revenue, it was enacted as part of a larger package whose scoring depends on the offsets within it, and the beneficiaries of repeal present as a small group of high volume gamblers rather than as a broad constituency. Bills that restore a deduction for that population do not carry themselves, and industry groups have not yet found a framing that makes repeal a general interest question.",
  "US tax and gaming counsel, including Ifrah Law PLLC, Greenberg Traurig LLP, Holland and Knight LLP and Duane Morris LLP, have noted that the change interacts awkwardly with the substantiation rules that govern gambling deductions in the first place. Losses must be substantiated, and the contemporaneous record keeping the Service expects has always been more demanding than most taxpayers appreciate. A limitation that increases the tax cost of every dollar of loss also increases the return on aggressive substantiation and the audit exposure of poor records. Taxpayers whose records were adequate under the old rule may find them tested more closely under the new one.",
  "There are second order effects on operators that have not yet worked through. High volume customers are a small proportion of accounts and a large proportion of handle in most sportsbooks, and a tax rule that makes marginal-edge play unprofitable after tax reduces that handle. It also increases the incentive for such players to move to venues that do not generate reportable US-source winnings, whether offshore books, peer-to-peer arrangements or prediction market venues whose contracts are taxed on a different basis. The competitive distortion between products taxed as gambling and products taxed as financial instruments is now larger than it was, and it did not arise from any decision about gambling policy.",
  "The IRS reporting threshold changes that accompanied the reform cut in the opposite direction on a narrower point. Raising the slot reporting threshold reduces the volume of information returns generated by machine play, which the industry has sought for years on operational grounds. It does not affect the deduction limitation, and it should not be read as evidence of a general direction of travel. The 2026 package tightened the treatment of losses while loosening a reporting formality, and the loosening is worth considerably less to affected taxpayers than the tightening costs them.",
  "For advisers, the practical guidance is unwelcome but clear. Clients with high gross volume should model their 2026 position on gross figures rather than on net results, should understand that a profitable year before tax may not be profitable after it, and should consider whether the volume that generates their edge is worth its tax cost. Some will find that reducing volume increases after-tax return, which is an unusual conclusion to reach about any activity and is the clearest indication that the limitation operates on a basis unrelated to ability to pay."
 ]
},
]

AUTHOR = "GamblingLawyers.com Editorial Team"


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,author:%s,author_slug:"",'
        'publish_date:%s,related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]), esc(a["title"]), esc(a["category"]), esc(a["excerpt"]),
            esc(AUTHOR), esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_06sep.bak")
        patch(p)
    print("done")
