#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-15 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))

ARTICLES = [
{
 "slug": "ukgc-stakelogic-slot-speed-supplier-product-design-2026",
 "title": "Slot Speed Breach Puts Game Suppliers on Notice",
 "category": "Compliance",
 "excerpt": "A £122,835 settlement over a 1.97 second spin cycle shows supplier licences carry product design duties no operator can absorb.",
 "publish_date": "2026-09-15T07:30:00Z",
 "related_jurisdictions": ["united-kingdom", "netherlands"],
 "related_firms": ["harris-hagan", "wiggin-llp", "joelson-llp", "kalff-katz-and-franssen"],
 "body": [
  "The Gambling Commission's regulatory settlement with Stakelogic BV, under which the supplier pays £122,835 in lieu of a financial penalty together with a contribution to investigation costs, concerns a difference of 0.53 seconds. The game Tiger Temple 88 completed a spin cycle in 1.97 seconds against the minimum 2.5 seconds required by the Remote Technical Standards since the October 2021 slots changes. There is no allegation of player harm attached to any identified customer, no money laundering finding and no suggestion that the supplier concealed anything. The case is worth close reading precisely because it is so narrow.",
  "Three features of the outcome should reset how supplier licensees think about their exposure. The first is that Stakelogic self-reported: the Commission's investigation began because the supplier told the regulator what it had found. The second is that the retest of the wider portfolio identified fifteen further games below the required cycle time, which converted a single defective title into a systemic finding about release and assurance processes. The third is that the licensee paying the settlement does not hold the customer relationship at all. Stakelogic supplies games that run on other operators' websites and apps, and the breach crystallised on those operators' platforms.",
  "That third point is the one most often misunderstood in commercial negotiation. British gambling counsel, including Harris Hagan, Wiggin LLP and Joelson LLP, have long had to explain to supply-side clients that a gambling software licence is not a business-to-business arrangement in which the operator carries the regulatory risk downstream. The supplier holds its own licence, is bound by the licence conditions and codes of practice in its own right, and is answerable for the compliance of the product it ships. An indemnity from the operator, however widely drafted, allocates money; it does not allocate regulatory liability, and it does not prevent a Commission finding attaching to the supplier's own licence record.",
  "The self-reporting dimension deserves a franker treatment than it usually receives. A supplier that discovers a technical breach faces an obvious temptation to fix it quietly, on the reasoning that disclosure converts a private defect into a public enforcement outcome. The Stakelogic result appears at first sight to vindicate that instinct, because disclosure produced a settlement. It does not. Licence condition 15.2.1 obliges licensees to report matters that may affect the regulator's assessment of their suitability, a six-figure settlement is a materially better outcome than a discovered and undisclosed breach, and a supplier whose games are tested by third parties and run on licensed operator platforms has no realistic expectation of a cycle time defect remaining unknown.",
  "The substantive lesson is about assurance architecture rather than about any single game. Game certification is generally a point-in-time exercise: a title is tested, certified and released, and the certificate speaks to the build that was tested. Spin timing, however, is affected by post-certification changes that are not obviously game changes at all, including engine updates, client rendering paths, animation settings, jurisdictional configuration switches and turbo or quick-spin features that were disabled in the tested build. A supplier that certifies at release and does not retest after those changes has assurance that tracks the certificate rather than the product actually being played.",
  "What the Commission expects instead is automated, continuous measurement of cycle time in production across every title and every market configuration, with the measurement running against the live game rather than a test harness. That is an engineering commitment, not a policy commitment, and it is one that many mid-sized suppliers have not made. Where it is absent, the honest position is that the supplier does not know its current cycle times; it knows what they were when each title was certified. Stakelogic's portfolio retest, which found fifteen further failures, is what that gap looks like when it is finally measured.",
  "For operators, the settlement is a reminder that content procurement is a compliance activity. An operator whose platform serves a non-compliant game is not insulated by the supplier's licence any more than the supplier is insulated by the operator's, and the operator is the party whose customers played the game. Supply agreements should require the supplier to warrant continuous technical standards compliance rather than certification at release, to notify the operator of any measured deviation within a defined period, and to permit the operator to withdraw a title immediately without commercial penalty. Dutch suppliers serving multiple European markets, whose counsel commonly includes firms such as Kalff Katz and Franssen, face the same analysis under the Netherlands framework with different numbers attached.",
  "The wider signal is that the Commission is now willing to spend enforcement resource on technical standards breaches that produce no identifiable victim, and to treat the product itself as a regulated object. Speed of play, autoplay restrictions, loss-disguised-as-win presentation, reverse withdrawal mechanics and celebratory feedback on losing outcomes all sit in the same category: design features that are prescribed because of their aggregate effect rather than because of any individual harm they can be shown to have caused. A supplier that can demonstrate what its products actually do in production, continuously, is in a defensible position. A supplier relying on release certificates is relying on a document that describes a build, not a game."
 ]
},
{
 "slug": "alberta-igaming-market-entry-aglc-registration-2026",
 "title": "Alberta's Open iGaming Market Tests Canadian Entry",
 "category": "Market Entry",
 "excerpt": "Canada's second competitive online market is live, and Ontario experience shortens the work without shortening the process.",
 "publish_date": "2026-09-15T08:15:00Z",
 "related_jurisdictions": ["canada", "united-states"],
 "related_firms": ["dickinson-wright-pllc", "greenberg-traurig-llp", "k-and-l-gates-llp"],
 "body": [
  "Alberta opened its competitive online gambling market on 13 July 2026, becoming the second Canadian province after Ontario to admit private operators, and the first assessment operators should make is structural rather than commercial. The iGaming Alberta Act, passed as Bill 48 in spring 2025, separates the functions that a single regulator performs in most jurisdictions. The Alberta Gaming, Liquor and Cannabis Commission retains regulatory oversight and registration, while a newly created provincial corporation, Alberta iGaming Corporation, holds the commercial relationship with operators. Entering the market therefore means satisfying two counterparties with different mandates, not one.",
  "The model is recognisably descended from Ontario's, where the Alcohol and Gaming Commission of Ontario registers operators and iGaming Ontario contracts with them as the conduct-and-manage entity. That lineage is the single most useful fact for an operator planning entry, because it means the disclosure burden, the corporate suitability analysis, the supplier registration requirement and the general shape of the operating agreement will be familiar to anyone who went through Ontario in 2022. It does not mean the work transfers. Registration in one province confers nothing in another, Canadian provincial gaming authority is constitutionally distinct, and Alberta has drafted its own requirements rather than adopting Ontario's.",
  "The practical consequence is that Ontario experience shortens preparation without shortening process. Materials assembled for the Ontario registration, including group structure charts, beneficial ownership disclosure, key individual submissions, financial statements, responsible gambling policies and anti-money laundering programmes, can largely be repurposed, and the institutional knowledge of how a Canadian provincial regulator assesses suitability is directly transferable. What cannot be compressed is the registration timetable itself, the separate supplier registrations for each gaming supplier in the operator's stack, and the negotiation of the commercial agreement with the provincial corporation.",
  "The three-stage registration route requires careful sequencing, particularly for operators whose content and platform supply chains are long. Every gaming-related supplier that provides services to a registered operator generally requires its own registration, and an operator cannot go live with content from a supplier that has not completed the process. Operators that treated supplier registration as a parallel workstream in Ontario, rather than a dependency, discovered that launch dates were set by their slowest supplier. Counsel with cross-border North American gaming practices, including firms such as Dickinson Wright PLLC, Greenberg Traurig LLP and K and L Gates LLP, routinely advise mapping the supplier chain and beginning those registrations before the operator's own file is complete.",
  "The commercial case for Alberta rests on a channelisation argument that operators should test rather than accept. Estimates placing roughly seventy per cent of current Alberta online gambling activity with unregulated operators imply a large addressable pool that regulation will convert. Ontario's experience suggests conversion is real but not automatic: it depends on the regulated proposition being competitive on product range, payment speed and promotional flexibility, and on the province enforcing against operators that decline to enter. An operator modelling Alberta on the assumption that the unregulated share transfers wholesale to licensed sites at current margins is modelling the best case.",
  "Advertising and responsible gambling rules are where Ontario's precedent is least reliable as a guide, because Ontario amended its standards materially after launch. The prohibition on using athletes in gambling advertising, restrictions on the promotion of inducements outside an operator's own channels, and successive tightening of what may be said to whom all arrived after operators had built their Ontario marketing plans. Alberta's framework is new and will develop, and the sensible planning assumption is that marketing restrictions will tighten rather than loosen. Marketing commitments, affiliate arrangements and sponsorship agreements should be drafted with that trajectory in mind.",
  "There is also a federal layer that provincial registration does not displace. Anti-money laundering obligations under the Proceeds of Crime (Money Laundering) and Terrorist Financing Act, reporting to FINTRAC, privacy obligations under federal and provincial regimes, and the Criminal Code provisions that make provincial conduct-and-manage authority the basis for lawful gambling all operate independently of the Alberta registration. Recent FINTRAC activity in the Canadian gaming sector has demonstrated that the federal regulator is willing to act against gaming entities, including those in public ownership, and an operator whose compliance planning stops at the provincial boundary has planned for part of the obligation.",
  "The strategic question for operators still deciding is whether a two-province Canadian market justifies the fixed cost of a Canadian operating structure. The answer depends on whether Alberta is treated as the second province or as evidence of a pattern. British Columbia and Quebec both run government-operated online offerings and both face the same unregulated-market argument that moved Ontario and Alberta, and an operator that builds Canadian registration capability now is positioned for any further province that opens. An operator that treats Alberta as a standalone case will rebuild the same capability from scratch the next time, and later than the competitors who did not."
 ]
},
{
 "slug": "finland-licence-application-review-supervisory-handover-2027",
 "title": "Finland's Licence Queue Runs Into a 2027 Handover",
 "category": "Licensing",
 "excerpt": "Applications are being assessed by the police board, but the agency that will supervise those licences takes over only in mid 2027.",
 "publish_date": "2026-09-15T09:00:00Z",
 "related_jurisdictions": ["finland", "sweden", "denmark"],
 "related_firms": ["schj-dt", "mannheimer-swartling", "bird-and-bird"],
 "body": [
  "Finland's dismantling of the Veikkaus monopoly for betting and online casino games is the most consequential licensing event in the Nordic region since Sweden opened in 2019, and its timetable contains a feature that operators preparing applications should plan around explicitly. The business-to-consumer application window opened on 1 March 2026. Licensed gambling services may not be provided until 1 July 2027, when the reformed Act enters into force in full. The National Police Board acts as licensing authority until the end of June 2027, after which supervisory competence passes to a new agency. The body that grants a licence, in other words, is not the body that will supervise it.",
  "This is not a drafting oversight, and comparable handovers have occurred elsewhere, but it has practical effects that are worth naming. An applicant cannot build a supervisory relationship with the authority that will actually regulate it, because that authority is not yet exercising the function. Informal guidance given during the application process by the licensing authority does not bind the successor. Interpretations of licence conditions that seem settled at grant may be revisited by a supervisor approaching the file without the negotiating history. Applicants should therefore document any material interpretation they rely on in writing, in the application itself, rather than resting on correspondence with an authority whose mandate expires.",
  "The gap between application and go-live creates a second, more commercial problem. An operator granted a licence in, say, late 2026 holds an authorisation it cannot exercise for months, during which it must maintain the corporate, financial and technical position described in its application. Ownership changes, group reorganisations, funding rounds, key personnel departures and platform migrations that occur in the interval are all potentially notifiable, and each carries a risk that the assessed position no longer matches the actual one. Groups contemplating transactions should assume that anything affecting control, financing or key individuals between grant and commencement will require disclosure.",
  "Nordic counsel advising on the reform, including firms with regional regulatory practices such as Schjødt, Mannheimer Swartling and Bird and Bird, have consistently identified the same analytical starting point: Finland has designed its framework with visibility of what did and did not work in Sweden and Denmark. Sweden opened with a licensing regime and a channelisation objective and has spent years addressing the gap between the two, tightening credit restrictions, payment controls and the territorial reach of its Gambling Act. Denmark paired licensing with supplier registration and aggressive website blocking. Finland's framework reflects both experiences, which means the enforcement posture from commencement is likely to resemble a mature market rather than a new one.",
  "Marketing is the area where the reform most changes the commercial calculus, and where the detail matters more than the headline. Moving from a monopoly, where advertising restrictions exist principally to limit the monopolist's own promotion, to a licensed market, where advertising is the mechanism by which licensed operators recruit players away from unlicensed ones, requires a different regulatory design. Operators should expect permitted advertising to be defined by reference to channel, content and audience rather than by volume, and should assume that affiliate activity conducted on their behalf is attributed to them. Affiliate contracts written for other markets are unlikely to satisfy that standard without amendment.",
  "The scope of what remains reserved is as important to model as what has been opened. The reform admits competition in betting and online casino games; Veikkaus retains exclusivity over other verticals, and the boundary between an opened category and a reserved one is where compliance risk concentrates. Product classification questions that look technical at the design stage, including how a given game format is characterised and whether a lottery-adjacent mechanic falls inside or outside the reserved scope, determine whether an operator is exercising its licence or offering an unauthorised product. These should be resolved before launch rather than after a supervisory query.",
  "Applicants should also be realistic about the sequencing of technical compliance. Registration and identification requirements, the national self-exclusion arrangements, reporting interfaces and any required technical connections to supervisory systems typically cannot be tested against production infrastructure until that infrastructure exists, and in a market commencing in July 2027 some of it will be built during the intervening period. Operators that schedule integration work for the final quarter before launch will be competing for the same technical support as every other licensee. Those that complete the commercially controllable parts early, including anti-money laundering programmes, responsible gambling logic and transaction reporting, retain flexibility for the parts they cannot control.",
  "The strategic question is timing rather than eligibility. Finland is a comparatively small, high-value market with a population that has gambled at high participation rates under the monopoly, and the operators that launch on day one will acquire players from a base that has no established relationship with any commercial brand. That advantage decays quickly. Against it stands the cost of holding an application-ready organisation through a long interval and the risk that requirements shift before commencement. Operators that intend to be in Finland at all should be in the first cohort, because the reason to enter this market is the transition itself, and the transition happens once."
 ]
},
{
 "slug": "germany-ggl-payment-blocking-swiss-psp-halle-court-2026",
 "title": "German Court Backs Payment Blocking Across Borders",
 "category": "Enforcement",
 "excerpt": "Halle's administrative court upheld a GGL blocking order against a Swiss payment provider, confirming reach over firms with no German presence.",
 "publish_date": "2026-09-15T09:45:00Z",
 "related_jurisdictions": ["germany", "switzerland"],
 "related_firms": ["hambach-and-hambach", "redeker-sellner-dahs", "cms-germany", "melchers-rechtsanw-lte"],
 "body": [
  "The Administrative Court in Halle has confirmed a decision of the Gemeinsame Glücksspielbehörde der Länder blocking a Swiss payment services provider from facilitating transactions for German customers, and the GGL has publicly framed the ruling as establishing that national borders are no obstacle to the enforcement of German gambling law. For payment institutions, platform providers and the operators that rely on them, the significance is not that payment blocking exists, which has been on the statute book since the 2021 State Treaty, but that it has now been judicially tested against a respondent outside Germany and outside the European Union.",
  "The statutory basis is the payment blocking power in the State Treaty on Gambling, which permits the supervisory authority to prohibit payment service providers from participating in payments connected with unlawful gambling, provided the authority has notified the provider of the unlawful offering. The provision was, for several years after the Treaty took effect, more discussed than used. That changed with the GGL's programme of formal blocking directives, reported in 2026 to have reached more than forty payment service providers, and with the willingness of the courts to uphold those directives on judicial review.",
  "German gambling counsel, including practices such as Hambach and Hambach, Redeker Sellner Dahs, CMS Germany and Melchers Rechtsanwälte, have consistently advised that the payment blocking route is more attractive to a regulator than direct action against offshore operators, and the reasoning is straightforward. An offshore operator with no German assets, no German establishment and no intention of appearing before a German court is a difficult enforcement target; a payment institution is regulated somewhere, holds authorisations it values, has correspondent relationships, and has a strong commercial interest in not being named in a blocking order. Enforcement is directed at the party that can be reached and has something to lose.",
  "The jurisdictional reasoning is what makes the Halle decision travel. A regulator asserting authority over a foreign payment provider must locate the connecting factor somewhere other than the provider's establishment, and the available candidates are the location of the customer, the direction of the service toward the German market, and the effect of the transaction within Germany. Each of these is a familiar basis for jurisdiction in consumer protection, data protection and competition law, and none of them requires the respondent to have any physical presence. A payment institution serving German cardholders on behalf of a merchant targeting Germany is, on that analysis, within reach regardless of where it is licensed.",
  "The practical difficulty for payment providers is that the obligation is one of classification rather than of transmission. A provider told to stop processing for unlawful gambling must determine which of its merchants are unlawful gambling operators, which requires it to know what its merchants actually do, whether they hold German authorisation, and whether the transactions it sees are connected to German players. Merchant category codes are a weak instrument for this: they are assigned by the acquirer, they are gamed, and they do not distinguish a German-licensed operator from an unlicensed one serving the same market. Providers that rely on coding alone are relying on a control that does not answer the question the order asks.",
  "The German enforcement campaign also needs to be read alongside the coordination among European regulators. The joint statement issued by authorities from Austria, France, Germany, Great Britain, Italy, Portugal and Spain called for harmonised payment blocking mechanisms, and the GGL's programme is effectively a working demonstration of what a coordinated mechanism would look like. A payment provider that treats the German directive as a German problem, and reconfigures its controls for German transactions alone, should expect materially similar demands from other regulators, and should design a control that takes jurisdiction as a parameter rather than a hard-coded assumption.",
  "For operators, the commercial implication is that payment relationships are now a regulatory dependency rather than a procurement matter. An operator serving Germany without German authorisation, or serving it in reliance on a contested legal analysis, exposes its payment partners to blocking orders, and payment partners respond to that exposure by terminating rather than litigating. The result is that enforcement against the operator is achieved through the commercial decisions of its counterparties, without any proceeding against the operator itself, and usually with contractual notice periods far shorter than a regulatory process would allow.",
  "The direction of travel is toward enforcement at infrastructure level generally, of which payment blocking is one instance and internet service provider blocking, advertising platform liability and app store removal are others. Each targets an intermediary that is identifiable, regulated and commercially rational, rather than an operator that is none of those things. Businesses that sit anywhere in the supply chain for online gambling, including payment institutions, hosting providers, affiliates and platform intermediaries, should assume that their exposure is determined by where their counterparty's customers are, not by where they themselves are established."
 ]
},
{
 "slug": "us-sweepstakes-litigation-racketeering-supplier-exposure-2026",
 "title": "Sweepstakes Risk Shifts From Bans to Racketeering",
 "category": "Regulatory",
 "excerpt": "Class actions, state consumer suits and Louisiana racketeering provisions move dual currency exposure onto suppliers and payment partners.",
 "publish_date": "2026-09-15T10:30:00Z",
 "related_jurisdictions": ["united-states"],
 "related_firms": ["ifrah-law-pllc", "zwillgen-pllc", "fox-rothschild-llp", "duane-morris-llp"],
 "body": [
  "The regulatory question about dual currency sweepstakes casinos in the United States has largely been answered: a growing number of states have prohibited the model outright, with Indiana's ban taking effect on 1 July 2026 and Maine's on 14 July 2026, and a substantially larger group has banned or effectively restricted the format through legislation, cease and desist activity or enforcement guidance. The more consequential development for counsel is what has replaced the regulatory question, which is a litigation and criminal exposure question, and it reaches parties that never considered themselves to be in the gambling business.",
  "Louisiana's legislation, signed in May 2026 and effective from 1 August 2026, is the clearest illustration. Rather than simply prohibiting dual currency gaming, the statutes attach racketeering exposure and penalties reported to reach one million dollars. A prohibition creates a compliance obligation to exit; a racketeering provision creates personal and organisational criminal exposure, potential predicate offences for federal purposes, and a basis for civil claims with enhanced damages. The difference matters most to individuals, because officers and directors who would face no personal consequence from a regulatory prohibition have a direct interest in the characterisation of conduct as racketeering.",
  "The civil litigation volume has grown to a point where it is the dominant commercial risk rather than a secondary one. Analyses published earlier in 2026 identified more than a hundred active class actions against sweepstakes operators across the United States, with VGW Holdings, the operator behind several of the largest dual currency brands, named in a substantial number. Many of these proceed under state loss recovery statutes, some of nineteenth century origin, which permit recovery of gambling losses and in several states permit recovery by persons other than the losing player. Those statutes do not require a regulator to act and are not answered by an operator's exit from the state.",
  "State consumer protection claims form the third strand. Florida's action against sweepstakes operators alleges both illegal gambling and violations of the Florida Deceptive and Unfair Trade Practices Act, and the pairing is deliberate. A deceptive practices claim does not require the court to resolve the contested question of whether a dual currency model constitutes gambling; it requires only that the presentation of the product to consumers was misleading. Where marketing emphasises the purchase of coin packages, the cash redemption value of a second currency and the appearance of casino play, a regulator has a viable claim regardless of how the underlying gambling characterisation is decided.",
  "The exposure of suppliers is the point most frequently underestimated. Game content providers, platform operators, payment processors, affiliates and marketing partners have generally treated the sweepstakes question as their customer's problem, on the basis that they neither operate the site nor hold the player relationship. Racketeering and conspiracy theories, aiding and abetting claims, and the inclusion of vendors as defendants in class actions all cut against that assumption, and United States gaming counsel including Ifrah Law PLLC, ZwillGen PLLC, Fox Rothschild LLP and Duane Morris LLP have been advising suppliers to conduct their own analysis rather than rely on their customer's.",
  "There is a specific and serious problem for suppliers that also hold state gaming licences. Licensing statutes generally require licensees to be of good character and to conduct their business in a manner that does not discredit the regulated industry, and supplying content to an operator that a different state has characterised as an illegal gambling enterprise is a suitability question in every state where the supplier is licensed. A supplier can therefore face an issue in its licensed jurisdictions arising from conduct that was lawful, or at least not clearly unlawful, where it occurred. The revenue from the sweepstakes channel rarely justifies that risk once it is stated in those terms.",
  "Exiting a state does not close the exposure, and this is the part operators most often get wrong. Withdrawal stops the accrual of new claims; it does not affect claims arising from historic play, and the limitation periods under state loss recovery and consumer protection statutes typically leave several years of past activity in scope. Nor does withdrawal assist with the characterisation of past conduct for licensing or criminal purposes. An operator that leaves a state after a ban takes effect has managed its forward compliance and left its accumulated liability untouched, which is why exit decisions should be taken alongside a reserve analysis rather than instead of one.",
  "For the broader industry, the sweepstakes episode is a case study in the limits of a structural workaround. The dual currency model was designed to place an activity outside the statutory definition of gambling by removing consideration, and for a period it succeeded, attracting substantial revenue and mainstream payment and marketing partners. What defeated it was not a single ruling that the analysis was wrong, but an accumulation of state legislation, private litigation and consumer protection enforcement, each on a different theory, none of which required the central legal question to be resolved. Any model whose viability rests on a definitional argument should be stress tested against that pattern rather than against the strength of the argument itself."
 ]
},
]

AUTHOR = "GamblingLawyers.com Editorial Team"


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,author:%s,author_slug:"",'
        'publish_date:%s,related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]), esc(a["title"]), esc(a["category"]), esc(a["excerpt"]),
            esc(AUTHOR), esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_15sep.bak")
        patch(p)
    print("done")
