#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-07 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))

ARTICLES = [
{
 "slug": "uk-gambling-commission-regulatory-burden-call-for-proposals-2026",
 "title": "UKGC asks the industry where to cut regulation",
 "category": "Regulatory",
 "excerpt": "The Commission's call for deregulatory proposals closes on 25 September. Operators get one chance to argue in the regulator's own language.",
 "publish_date": "2026-09-07T07:30:00Z",
 "related_jurisdictions": ["united-kingdom"],
 "related_firms": ["harris-hagan", "wiggin-llp", "northridge-law-llp", "joelson-llp"],
 "body": [
  "The Gambling Commission has invited licensees to identify requirements in the licence conditions and codes of practice that impose cost without advancing the licensing objectives, with submissions closing on 25 September 2026. Read casually, this is a housekeeping exercise of the sort every regulator runs periodically. Read carefully, it is the most significant procedural opportunity the licensed sector has had since the White Paper implementation programme began, and it is structured in a way that most operators are poorly equipped to exploit.",
  "The framing matters more than the invitation. The Commission has not asked which rules operators dislike, nor which rules are expensive. It has asked which rules impose burden disproportionate to their contribution to the three statutory licensing objectives: keeping gambling free of crime, ensuring it is conducted fairly and openly, and protecting children and vulnerable persons. That is a test with a defined structure. A submission that establishes cost but not disproportion has answered a question that was not asked, and a submission that asserts disproportion without evidence on either side of the comparison cannot be acted on even by a regulator sympathetic to it.",
  "British gambling counsel, including Harris Hagan, Wiggin LLP, Northridge Law LLP and Joelson LLP, have consistently advised that submissions of this kind succeed on the quality of the counterfactual rather than the intensity of the complaint. The persuasive form is narrow and evidential: this specific provision generates this measurable cost, produces this measurable regulatory output, and the objective it serves is already secured by this other provision or could be secured by this less costly alternative. The unpersuasive form is a general statement that the regime has become burdensome, which the Commission has heard continuously for a decade and which gives it nothing to act on.",
  "There is a strategic risk in the exercise that operators should weigh before submitting. Anything a licensee describes as burdensome is, by implication, something it is currently doing at cost, and a submission is a disclosure about the operator's own compliance architecture. An operator that argues a particular reporting requirement generates no useful signal is telling the regulator what its own monitoring produces. An operator that argues a control is duplicative is asserting that another control covers the same ground, which is a representation the Commission may test at the next assessment. Submissions should be drafted on the assumption that they will be read back to the operator during a compliance review.",
  "The wider context is a regulator under simultaneous and opposing pressures. The Commission has been given additional funding to pursue the illegal market, has published a national risk assessment classifying every major sector as high risk for money laundering, and continues to conclude substantial enforcement settlements against licensees. It is also operating within a government policy environment that has made regulatory burden reduction a general objective across sectors. Those pressures are not reconcilable in principle, and the call for proposals is one of the mechanisms by which the Commission will decide where to release pressure without conceding ground on the objectives it is judged against.",
  "That suggests where submissions are most likely to land. Requirements that generate administrative output nobody uses, duplicative reporting across returns that ask for the same data in different formats, and prescriptive process rules that survive from an earlier technical era are all plausible candidates, because relaxing them costs the Commission nothing in objective terms. Requirements that bear directly on affordability, on marketing to vulnerable customers, or on anti-money laundering controls are not plausible candidates, whatever the cost evidence, because the Commission cannot relax them without exposing itself on the objectives. Operators who spend their submission on the second category will have spent it for nothing.",
  "There is also a collective action question that the sector has not resolved. Individual operators submitting individually will produce a set of overlapping and partly inconsistent asks, and a regulator confronted with fifty different views on which provisions are disproportionate is entitled to conclude that none of them is clearly so. Trade bodies can consolidate, but consolidation dilutes the evidential specificity that makes a submission actionable. The strongest position is probably a small number of well evidenced individual submissions on distinct provisions, coordinated to avoid contradiction, rather than either a single trade position or an uncoordinated flood.",
  "Whatever the outcome, the process establishes a record. A licensee that identifies a requirement as disproportionate in September 2026 and is later found in breach of it will face the obvious question, and a licensee that stays silent forfeits any later complaint that the Commission did not ask. Operators should treat the deadline as a genuine one, should commit legal and compliance resource to the drafting rather than delegating it to a public affairs function, and should recognise that the submission is a regulatory communication with the same standing as any other."
 ]
},
{
 "slug": "sweden-credit-funded-gambling-ban-payment-controls-2026",
 "title": "Sweden's credit ban makes operators police payments",
 "category": "Compliance",
 "excerpt": "Sweden is the first EU state to bar all credit-funded gambling, pushing licensees into a payment-source verification role they were never built for.",
 "publish_date": "2026-09-07T08:20:00Z",
 "related_jurisdictions": ["sweden", "denmark"],
 "related_firms": ["mannheimer-swartling", "delorean-advokat", "bird-and-bird", "cms"],
 "body": [
  "Sweden's extension of the credit prohibition under the Gambling Act (2018:1138) has made it the first EU member state to bar gambling funded by credit in every form, and the obligation now sits on licensees rather than on lenders. Licensed operators and their agents may not accept deposits funded by credit cards, overdraft facilities, personal loans, invoice credit or buy now pay later arrangements, and may not permit or facilitate gambling funded by deferred payment of any kind. The drafting is deliberately wide, and its width is the compliance problem.",
  "The original prohibition was narrow and workable because it addressed credit extended by the operator itself. An operator knows whether it has lent to a customer. The extended prohibition addresses the origin of the customer's money, which the operator does not know and, on conventional payment rails, cannot readily discover. A deposit arriving by open banking transfer from a current account tells the operator nothing about whether that account was in credit, in an arranged overdraft, or funded that morning by a consumer loan. The obligation is therefore to prevent something the operator cannot see, and Swedish counsel including Mannheimer Swartling and Delorean Advokat have identified this as the central interpretive question of the reform.",
  "Two readings of the standard are possible and they produce very different compliance builds. The strict reading treats the prohibition as absolute, so that any deposit in fact funded by credit is a breach whatever the operator knew, which would require operators to verify the funding source of every deposit before accepting it. The reasonable steps reading treats the operator's obligation as one of design and diligence, so that an operator that blocks identifiable credit instruments, screens for known credit-linked payment methods and acts on indications of credit funding has complied even if some credit-funded money gets through. The second reading is the one operators are building to, and the regulator has not foreclosed the first.",
  "The immediately actionable layer is card BIN screening, which is mature technology and covers the clearest case. Blocking credit card BINs while permitting debit is standard across markets that have banned credit card gambling, and the residual problems are known: BIN ranges that mix products, prepaid and virtual cards issued against credit facilities, and commercial cards that do not classify cleanly. Buy now pay later is harder in a different way, because those providers present at the payment page as ordinary payment methods and because the credit character of the transaction sits with the provider rather than in the instrument. Operators need to remove those providers from the Swedish payment mix entirely rather than attempt to screen them.",
  "Overdrafts and personal loans are where the reasonable steps reading does the most work. A licensee cannot see an arranged overdraft on an incoming bank transfer, and any attempt to infer one from transaction data would raise its own problems under data protection law. What the licensee can do is act on what it already holds. Deposit patterns consistent with borrowing, customer disclosures made during affordability interactions, and information surfaced by open banking where the customer has consented to share it are all signals the operator possesses, and a regime that ignores signals in its own systems will not be defended as diligent. The obligation, in practice, is to connect the credit prohibition to the affordability function rather than to build a separate payment forensics capability.",
  "The enforcement dimension has changed alongside the substantive rule. Spelinspektionen's sanctioning powers have been expanded, and the available responses to non-compliance run from financial penalties through operating restrictions to licence revocation. That matters because the credit prohibition is the kind of obligation that produces continuous low level breach rather than discrete incidents. A regulator assessing a licensee will not find a single failure to prosecute; it will find a rate, and the question will be whether the rate reflects an adequate control environment. Operators should be measuring and documenting that rate themselves, because the alternative is having it measured for them.",
  "Two further changes compound the effect. The removal of the directional criterion means the Gambling Act now reaches any operator making services available to Swedish players regardless of the language or currency used, closing the route by which offshore operators argued they were not targeting Sweden. Combined with the credit ban, this creates a sharp divergence between the licensed market, where credit funding is impossible, and the unlicensed market, where it is not. Sweden's channelisation rate has been contested for years, and the reform gives the offshore sector a genuine product advantage for exactly the cohort of players the ban is designed to protect.",
  "That tension will define how the reform is judged. If credit-funded play migrates offshore rather than stopping, the policy will have transferred harm rather than reduced it, and the enforcement response will have to come from the blocking and payment disruption side rather than from licensee supervision. Operators licensed in Sweden should assume that they will be held strictly to the prohibition regardless of what the unlicensed market does, should document their control design and its limits now, and should be prepared to show the regulator not that no credit-funded deposit ever reached them, but that their system was built to stop the ones it could see."
 ]
},
{
 "slug": "italy-adm-concession-eligibility-eu-establishment-2026",
 "title": "Italy raises the bar for online concession applicants",
 "category": "Market Entry",
 "excerpt": "ADM now requires EU or EEA incorporation, an Italian registered office for tax, and certified management systems before a concession is granted.",
 "publish_date": "2026-09-07T09:15:00Z",
 "related_jurisdictions": ["italy", "malta"],
 "related_firms": ["dla-piper-italy", "studio-legale-sbordoni-and-partners", "cms-italy", "norton-rose-fulbright-italy"],
 "body": [
  "Italy's reorganised online concession regime has moved the qualifying criteria for market entry from financial capacity toward corporate substance and certified governance, and the shift changes which operators can realistically apply. A company seeking a concession must now be incorporated within the European Union or the European Economic Area and, if not established in Italy, must maintain a registered office within Italy for tax purposes. Applicants must also demonstrate adherence to recognised international standards, with certification under ISO 9001 for quality management, ISO 26000 for social responsibility and ISO 27001 for information security forming part of the qualifying package.",
  "The EU or EEA incorporation requirement is the provision with the widest exclusionary effect. It removes from eligibility a substantial part of the operator population that services European markets through structures incorporated in the Caribbean, in Asia or in other third countries, regardless of the quality of those operations or the licences they hold elsewhere. An operator whose group parent sits outside the EEA cannot apply from that entity and must establish an EEA-incorporated applicant with genuine standing to hold the concession, which is a corporate reorganisation rather than an application formality.",
  "The Italian registered office requirement is directed at tax certainty rather than at operational presence, and its consequences are principally fiscal. An office maintained in Italy for tax purposes puts the concessionaire within reach of Italian tax administration in a way that a purely remote operator would not be, and raises questions about permanent establishment, transfer pricing between the Italian entity and the group platform, and the allocation of profit to the Italian activity. Italian gaming and tax counsel, including DLA Piper Italy, Studio Legale Sbordoni and Partners, CMS Italy and Norton Rose Fulbright Italy, have advised that the tax structuring analysis needs to be run before the concession application rather than after the award, because the structure adopted to satisfy the requirement determines the tax profile of the Italian business for the life of the concession.",
  "The ISO requirements are the most novel element and the most often underestimated. These are certifications rather than declarations, requiring an accredited external audit against a documented management system, and the certification cycle for an organisation starting without one typically runs to several months of preparation before the audit can be scheduled. ISO 27001 in particular demands a functioning information security management system with defined scope, a risk treatment methodology, documented controls and evidence of operation over a period. An applicant that discovers the requirement when preparing its bid has already lost the time needed to satisfy it.",
  "The scoping of those certifications deserves attention because it is where group operators most often go wrong. A certificate held by a group parent covering a platform operated from another jurisdiction does not necessarily cover the Italian concessionaire entity or the systems that serve the Italian market. If the certification scope statement does not encompass the applicant and the relevant operations, the certificate answers a different question than the one the concession requires. Extending scope to a newly incorporated Italian entity is possible but adds an audit cycle, which again is time that must be found before the application window rather than during it.",
  "Read together, these criteria describe a deliberate policy choice about the composition of the Italian market. Italy has priced its concessions at a level that already favours well capitalised operators, and the substance and certification requirements narrow the field further toward established groups with existing European corporate structures and mature compliance functions. The effect is fewer, larger concessionaires, each carrying a higher fixed cost and each more visible to the regulator. Whether that improves consumer outcomes is an open question, but it certainly improves supervisory tractability, which is a recognisable objective across European regulators at present.",
  "For operators licensed elsewhere in Europe the practical route into Italy now runs through an assessment of what the existing group already satisfies. An operator holding a Malta licence through an EU-incorporated entity with group-level ISO 27001 certification is closer to eligibility than the requirements first suggest, and its work is scoping and tax structuring rather than reconstruction. An operator holding a Curacao licence through a non-EEA parent, with no certified management systems, is looking at a programme measured in quarters. The gap between those two positions is the real barrier to entry, and it is not one that capital alone closes quickly.",
  "The advice to prospective entrants is therefore to sequence the work against the concession timetable rather than against the commercial plan. Corporate establishment, tax structuring and certification are independent workstreams with different lead times, and the longest of them, certification, is the one least amenable to acceleration by spending. Operators intending to enter Italy in the next concession cycle should be starting the certification process now, on a scope statement drafted to cover the entity that will hold the concession, and should treat the application itself as the last step rather than the first."
 ]
},
{
 "slug": "malta-mga-2026-supervisory-agenda-crypto-adr-integrity",
 "title": "MGA's 2026 agenda targets crypto, ADR and integrity",
 "category": "Enforcement",
 "excerpt": "With penalties past 2.8m euros and four licences suspended, the MGA has told licensees exactly where its next enforcement wave will land.",
 "publish_date": "2026-09-07T10:00:00Z",
 "related_jurisdictions": ["malta"],
 "related_firms": ["camilleri-preziosi", "wh-partners", "gvzh-advocates", "ellul-and-co"],
 "body": [
  "The Malta Gaming Authority's enforcement record for the year, with financial penalties exceeding 2.8 million euros and four operator licences suspended for failures spanning anti-money laundering deficiencies and unauthorised game offerings, is best read alongside the supervisory agenda that sets out where the Authority intends to look next. Regulators that publish their priorities are making a choice about how enforcement operates: a licensee that fails in a named priority area has failed in an area it was told would be examined, and the argument that a deficiency was not reasonably foreseeable becomes unavailable.",
  "Crypto asset internal controls head the list, and the Authority's interest is narrower and more technical than the general debate about cryptocurrency in gambling suggests. The MGA has permitted virtual financial asset acceptance under defined conditions for several years, and the supervisory question is not whether an operator may accept them but whether the controls around them function. That means the adequacy of source of funds verification where the funds arrive as tokens with no banking trail, the reliability of blockchain analytics screening against sanctioned and high risk addresses, the treatment of volatility between deposit and wager, and the segregation and valuation of player balances held in a fluctuating asset for the purposes of the player funds requirements.",
  "Alternative dispute resolution reporting quality is the second priority and the one operators consistently underrate. Malta requires licensees to make ADR available and to report on player complaints, and the reporting has historically been treated by many licensees as an administrative return of low consequence. The Authority's focus on quality signals that it now reads those returns as a supervisory dataset. Complaint volumes, categories, resolution rates and time to resolution together describe how a licensee treats its customers, and inconsistency between what an operator reports and what the ADR entities record is a discrepancy the Authority can identify without visiting the operator at all.",
  "Sports betting integrity completes the agenda and reflects pressure from outside the Maltese regulatory perimeter. Malta licenses a substantial proportion of the operators serving European sports betting markets, which places the Authority in the path of integrity intelligence flowing from sports governing bodies, national regulators and monitoring organisations across the continent. The supervisory questions are whether licensees have functioning suspicious betting detection, whether they report to the appropriate bodies within required timeframes, and whether commercial considerations affect what gets reported. Maltese counsel, including Camilleri Preziosi, WH Partners, GVZH Advocates and Ellul and Co, have noted that integrity obligations are among the few where a licensee's interests and its regulatory duties can diverge directly.",
  "The suspensions are the more instructive part of the enforcement record. A financial penalty is a cost that a licensee absorbs and continues trading through; a suspension stops the business, and the pairing of grounds cited, anti-money laundering deficiencies and unauthorised game offerings, tells operators something about how the Authority calibrates. Anti-money laundering failures are systemic and are treated as evidence that the control environment as a whole cannot be relied upon. Unauthorised game offerings are discrete and are treated as evidence that the licensee does not control its own product perimeter. Either supports the conclusion that continued operation presents unacceptable risk, which is the threshold a suspension has to clear.",
  "Running alongside formal enforcement is the Authority's steady output of notices disowning URLs that impersonate MGA licensees or claim MGA authorisation they do not hold. Clone sites are a persistent problem for Malta precisely because the licence carries reputational weight with players, and the burden of the problem falls partly on legitimate licensees whose brands are copied. Operators should be monitoring for impersonation actively rather than relying on the Authority's notices, because the commercial damage occurs during the period before a notice is published and because takedown is faster when the brand owner initiates it.",
  "The strategic position for Malta remains uncomfortable in a way the supervisory agenda cannot resolve. The jurisdiction is defending its Article 56A protections against European Commission infringement proceedings, is absorbing the gaming tax and capital changes that have raised the cost of holding a licence, and is competing against national licensing regimes in the markets its licensees serve. Visible and rigorous enforcement is Malta's principal answer to the argument that the licence is a light touch product, and each suspension is worth more to that argument than the fines are.",
  "Licensees should treat the agenda as an examination syllabus. Where an operator accepts virtual financial assets, the controls should be documented and tested before the Authority arrives rather than described to it afterwards. Complaint and ADR reporting should be reconciled against the ADR entities' own records. Integrity reporting should be reviewed for cases that were considered and not reported, with reasons recorded. None of that is novel compliance work, but the difference between an operator that has done it and one that has not becomes visible immediately in a supervisory engagement, and the Authority has now removed any doubt about where it will be looking."
 ]
},
{
 "slug": "germany-interstate-treaty-2026-evaluation-ip-blocking-powers",
 "title": "Germany's treaty review turns on enforcement powers",
 "category": "Licensing",
 "excerpt": "The first full evaluation of the 2021 Interstate Treaty is under way, with site blocking and half the online market still unlicensed at its centre.",
 "publish_date": "2026-09-07T10:45:00Z",
 "related_jurisdictions": ["germany", "austria"],
 "related_firms": ["hambach-and-hambach", "redeker-sellner-dahs", "cms-germany", "bird-and-bird"],
 "body": [
  "The first comprehensive evaluation of Germany's Interstate Treaty on Gambling since it took effect in 2021 is now under way, and the state interior ministers have been pressing for reform ahead of it rather than waiting for its conclusions. That sequencing is revealing. A review conducted after political agreement on the direction of travel is an exercise in justifying decisions already taken, and licensees should plan on the assumption that the substantive questions are being settled in the negotiations between the states rather than in the evaluation itself.",
  "The central factual problem is not disputed by anyone. Independent research indicates that roughly half of German online gambling revenue flows to operators outside the licensed system. A regime that captures half of its market has failed on channelisation by any standard applied elsewhere in Europe, and the licensed sector has consistently attributed the shortfall to the restrictiveness of the product rules: the monthly deposit limit applied across operators, the mandatory intervals between slot spins, session break requirements and the absence of product categories that players can obtain without difficulty from unlicensed sites. The counter-argument, that the licensed product is protective by design and that the answer lies in enforcement rather than liberalisation, is the one that appears to be prevailing.",
  "Enforcement is where the reform proposals are most concrete. The Gemeinsame Gluecksspielbehoerde der Laender has been constrained since a 2023 court decision struck down its attempt to block access to an offshore operator, leaving it without a reliable legal basis for network level blocking. Draft treaty provisions are directed squarely at that gap, seeking to establish a foundation for IP blocking and content takedown that survives judicial review. German gambling counsel, including Hambach and Hambach, Redeker Sellner Dahs, CMS Germany and Bird and Bird, have noted that the drafting problem is not the power itself but its proportionality: a blocking regime must be targeted, subject to procedural safeguards and capable of correction, or it will fail on the same grounds as its predecessor.",
  "The proposals also extend the regulator's reach in licensing and supervision in ways that will affect licensed operators more than offshore ones. Provisions allowing the GGL to request background checks from authorities in other jurisdictions during licensing assessment, and to establish formal information sharing arrangements for ongoing monitoring, would change the evidential basis for suitability decisions. An applicant whose group has a regulatory history in Malta, the United Kingdom or a US state would find that history directly available to the German regulator rather than reconstructible only from public sources, and adverse findings elsewhere would carry weight in Germany that they currently do not.",
  "For existing licensees this raises a live question about continuing suitability. Suitability in most regimes is assessed at application and re-examined on renewal or on the occurrence of a reportable event, and the practical constraint on continuous assessment has always been the regulator's access to information. Remove that constraint and the position changes: a settlement concluded with another European regulator becomes something the GGL may learn of directly and promptly. Operators holding German licences alongside licences elsewhere should be reviewing their notification obligations in Germany against what an information sharing arrangement would surface anyway.",
  "The deposit limit remains the most contested product rule and the one with the least satisfactory current answer. The cross-operator monthly limit of 1,000 euros can be raised for individual players subject to an affordability assessment, but the criteria for that assessment have never been settled with sufficient precision for operators to apply them confidently. The result is a rule that constrains ordinary players while providing an uncertain path for those who could evidence higher capacity, and operators have understandably defaulted to the restrictive interpretation. Clarifying the affordability standard would do more for channelisation than most of the alternatives, and it is achievable without conceding the principle of the limit.",
  "Licensing volumes tell their own story about the market's trajectory. The online casino licence pool has grown from its initial cohort as further permissions have been granted, but the expansion has been gradual and the licensed population remains small relative to the number of operators serving German players. A regime that licenses slowly while half the market operates outside it faces an obvious criticism, and the evaluation will have to address whether the licensing process itself contributes to the channelisation gap by keeping willing applicants outside the system longer than necessary.",
  "The realistic forecast is a reform package that strengthens enforcement substantially and adjusts product rules marginally. That combination is politically deliverable because it concedes nothing on consumer protection while giving the regulator the tools it says it lacks, and it is the outcome the ministers' early positioning points toward. Whether it moves channelisation is a different question, and one that Germany will only be able to answer at the next evaluation. Operators should prepare for a German market in which offshore competition is materially harder to sustain, in which the regulator knows considerably more about their conduct in other jurisdictions, and in which the product they may lawfully offer looks much as it does today."
 ]
},
]

AUTHOR = "GamblingLawyers.com Editorial Team"


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,author:%s,author_slug:"",'
        'publish_date:%s,related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]), esc(a["title"]), esc(a["category"]), esc(a["excerpt"]),
            esc(AUTHOR), esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_07sep.bak")
        patch(p)
    print("done")
