#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-10-02 into _source.html and app.js."""
import os, shutil, importlib.util
BASE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("base30", os.path.join(BASE, "insert_articles_30sep.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

ARTICLES = [
{
 "slug": "brazil-mp-1394-betting-ban-licence-fee-compensation-claims-2026",
 "title": "Brazil's Betting Ban: Licence Fee and Compensation Claims",
 "category": "Licensing",
 "excerpt": "Provisional Measure 1.394 ends licensed online betting but keeps licence fees. Operators now weigh court challenges and compensation routes.",
 "publish_date": "2026-10-02T06:30:00Z",
 "related_jurisdictions": ["brazil", "portugal", "united-kingdom"],
 "related_firms": ["pinheiro-neto-advogados", "mattos-filho", "bird-and-bird"],
 "body": [
  "Reports from 25 to 29 September 2026 describe Provisional Measure 1.394, signed by President Lula on 25 September, as an immediate prohibition on online betting and online casino activity by licensed operators. Coverage indicates that sites and apps must go offline by 6 October, that bettors have until 23:59 on 5 October to withdraw balances, and that refunds will be processed until 14 October with the state bank Caixa Econômica Federal handling transfers that are not completed. We have relied on press reports rather than the published text, so operators should read the measure itself before acting.",
  "The most commercially sensitive point is the position on licence fees. Roughly 90 operators are reported to have paid in the region of 30 million reais each for authorisations that were originally valid until 2029. The Finance Minister is quoted as rejecting refund demands and describing the licences as a precarious arrangement valid only for that moment. That characterisation is a political statement, not a legal conclusion, and it will be tested against the Brazilian legal doctrine that protects legitimate expectations and requires a public authority to compensate for lawful acts that impose a special and abnormal burden on identifiable parties.",
  "Operators have at least three procedural routes. The first is a direct challenge to the provisional measure before the Supreme Federal Tribunal, which the industry associations IBJR and ANJL have said they will pursue. The arguments are likely to focus on whether the constitutional requirements of relevance and urgency for a provisional measure are met, on legal certainty for authorisations granted under a statutory framework, and on proportionality of a total prohibition when less restrictive tools were available. The second is an ordinary damages or restitution claim against the Union for the unamortised value of the licence fee and sunk investment. The third is a negotiated settlement, for example credit against future fees if the framework is later restored.",
  "Congress has 120 days to convert or reject the measure. If it lapses or is rejected, the earlier licensing framework would be restored, which gives the industry a political path as well as a judicial one, and reports suggest lobbying will intensify after the first round of the presidential election on 4 October. Counsel should treat that timetable as a planning variable. A claim for compensation is stronger if the measure is made permanent, whereas a restored regime may reduce the loss and narrow the relevant period of suspension.",
  "In the meantime the wind-down is a compliance exercise in its own right. Operators must cancel unsettled bets, return balances, preserve player records and maintain anti-money-laundering controls for the transactions that occur during the exit window. Unclaimed balances that pass to Caixa raise questions about data transfers, retention and the treatment of players who are self-excluded or subject to open investigations. Contractual consequences also need review, including supplier and affiliate agreements, sponsorship commitments and payment-service provider terms that may contain force majeure, termination or minimum-volume clauses.",
  "Group-level issues should not be overlooked. Brazilian subsidiaries that fall into loss, impairment or insolvency can trigger covenant, disclosure and licence notification duties in other jurisdictions where the parent is licensed, and regulators such as the UK Gambling Commission expect prompt notification of key events. Shareholders and lenders will ask whether the Brazilian investment is a total loss, a suspended asset or a contingent claim, and the answer determines how it is accounted for. Where bilateral or multilateral investment protection treaties could apply, structuring advice on the holding chain becomes relevant, although the eligibility of gambling licences as protected investments depends on the specific treaty wording.",
  "The broader lesson for licensing strategy is that a licence is only as stable as the political settlement behind it. Market-entry decisions should now include a scenario analysis for abrupt policy reversal, covering fee recovery, wind-down costs and the speed at which illegal operators fill the vacuum. Firms advising on this matter in Brazil, such as Pinheiro Neto Advogados and Mattos Filho, together with international teams like Bird and Bird, can help operators map the claims, the deadlines and the evidence they need to preserve now."
 ]
},
{
 "slug": "brazil-betting-ban-illegal-operator-surge-bet-legal-enforcement-exposure-2026",
 "title": "Brazil Ban Fuels Illegal Operators: Enforcement Risk",
 "category": "Enforcement",
 "excerpt": "Monitoring data show illegal betting sites in Brazil rising from 102 to 575 within days. Payment and affiliate exposure follows.",
 "publish_date": "2026-10-02T07:20:00Z",
 "related_jurisdictions": ["brazil", "united-kingdom", "malta"],
 "related_firms": ["pinheiro-neto-advogados", "mattos-filho", "pinsent-masons-llp"],
 "body": [
  "Within days of the announcement of Brazil's online betting ban, monitoring data indicates a sharp rise in unlicensed operators targeting Brazilian players. Figures attributed to the Bet Legal monitoring platform and reported on 29 September 2026 show 102 illegal operators detected on 21 September, 331 on 26 September and 575 on 29 September, with other coverage reporting that around 700 illegal sites had emerged within 48 hours of the announcement. The counts come from a private monitoring tool and are not an official regulatory statistic, but the direction of travel is consistent with what regulators have long warned about when a regulated market is closed.",
  "The legal significance is that enforcement priorities change overnight. Before the ban, the regulatory architecture was built around a licensed channel, with the Secretariat of Prizes and Bets supervising approved operators and cooperating with payment providers and telecom authorities to block unlicensed offers. If licensed supply is prohibited, the enforcement question is no longer how to push players toward licensed brands but whether the state has the capacity to police a market where every operator is, by definition, outside the law.",
  "Payment institutions are the most exposed group. Brazil has already used payment-flow controls to cut off illegal gambling, and a surge in unlicensed sites increases the volume of suspicious transactions that banks, Pix participants and payment service providers must screen. Institutions that continue to process flows to sites that later prove to be illegal face administrative, civil and potentially criminal exposure, particularly where red flags such as foreign merchant descriptors, mule accounts or sudden volume spikes were visible. Compliance teams should refresh typologies and escalate gambling-related alerts now rather than waiting for supervisory guidance.",
  "Affiliates, influencers and media owners face a parallel risk. Brazilian authorities and courts have shown willingness to pursue those who promote illegal betting, and the legal position of an affiliate that previously promoted licensed brands but now sees those brands offline is delicate. Redirecting traffic to an unlicensed operator, even one that is lawful in another country, can convert a compliant business into an infringing one. Contracts should be reviewed for clauses that prohibit promotion of unlicensed products and that allow immediate suspension of campaigns.",
  "International licensees must consider reputational and regulatory spillover. A group that holds a licence in Malta, the United Kingdom or elsewhere may be asked whether any entity in the group continues to accept Brazilian players through a non-Brazilian licence once the local authorisation is withdrawn. Licensing conditions in several jurisdictions require operators not to accept bets from territories where the activity is unlawful, and a decision to keep serving Brazil from an offshore licence would invite scrutiny of fitness and propriety, including how the business responds to a local prohibition.",
  "Players are also affected. Funds held in unlicensed accounts are not protected by any regulatory safeguard, and the risk of unfair terms, withheld withdrawals and data misuse rises. Consumer protection bodies and public prosecutors may act to warn players and to pursue those who market to vulnerable groups. Advertising rules that applied to licensed betting will not discipline illegal sites, so enforcement will rely heavily on blocking orders, payment disruption and criminal investigation of organised networks.",
  "The practical advice is to treat the next several months as a high-risk period. Licensed operators winding down should log their exit steps and avoid any activity that could be characterised as continuing to serve the market. Payment providers and affiliates should audit their Brazil-facing exposure. Local counsel, including firms such as Pinheiro Neto Advogados and Mattos Filho, and international teams like Pinsent Masons, can assist with risk assessments, regulatory engagement and investigations if an enforcement request arrives."
 ]
},
{
 "slug": "netherlands-ksa-lotto-bv-exclusive-licences-extension-monopoly-challenge-2026",
 "title": "Dutch KSA Extends Lotto BV Licences Despite Monopoly Case",
 "category": "Licensing",
 "excerpt": "The KSA renewed Lotto BV's exclusive licences while a Council of State case tests the monopoly. The review clause is the key detail.",
 "publish_date": "2026-10-02T08:05:00Z",
 "related_jurisdictions": ["netherlands", "belgium", "germany"],
 "related_firms": ["kalff-katz-and-franssen", "stibbe", "akd-benelux-lawyers"],
 "body": [
  "On 15 September 2026, according to trade press, the Dutch Gambling Authority (KSA) extended the exclusive licences of Lotto BV covering lottery games, sports betting and scratch products for five-year terms, even though a case before the Administrative Jurisdiction Division of the Council of State questions whether the Dutch monopoly respects competitive fairness. Reports add that the KSA said any change to Lotto BV's licence status would occur no earlier than one year after the Council of State rules. We have not reviewed the decisions themselves, so this commentary is based on the reported terms.",
  "The decision illustrates a familiar tension in gambling regulation between continuity and legal uncertainty. A regulator facing an expiring permit can either extend it on the existing legal basis or leave a gap that would interrupt a service that the state treats as a public-interest activity. The KSA chose continuity, and in doing so signalled that it regards the operative framework as lawful until a court says otherwise. The review mechanism, which delays any adjustment until a year after the ruling, is designed to give the legislature and the regulator time to restructure the market if the court finds a flaw.",
  "The legal question underneath is whether a monopoly can be justified under the standards that European and Dutch law apply to restrictions on the freedom to provide services. The Court of Justice of the European Union has accepted monopolies in principle where they pursue consistent and systematic objectives such as preventing gambling addiction and crime, but it has also held that a monopoly cannot be justified if the holder pursues expansionist commercial policies that undermine those objectives. The Dutch case is framed around competitive fairness, which suggests that the court will examine how the monopoly holder operates alongside the licensed online market and its advertising.",
  "Reported scenarios include maintaining exclusivity, introducing a competitive licensing regime or abolishing the monopoly altogether, which would require a privatisation review. Each has distinct consequences. A competitive regime would open sports betting and lottery products to private operators and create a new market-entry window in a jurisdiction that already has a developed remote casino regime. Abolition would raise questions about the treatment of Lotto BV's existing licence and any compensation. Maintenance would end a period of uncertainty but could strengthen the position of the monopoly holder.",
  "For private operators the practical implication is to monitor the case and prepare options rather than to build a business plan around an uncertain outcome. Potential entrants can model licence conditions, fees, tax and safer-gambling obligations drawing on the Remote Gambling Act experience, and can assess whether existing Dutch remote licences might be extended or complemented. Those already licensed should consider how any liberalisation would affect product scope, advertising rules and the competitive position of their brands.",
  "Investors and suppliers to Lotto BV should also review contract terms. Change-of-law clauses, termination rights and long-term supply or distribution agreements may be sensitive to a restructured market. If the monopoly is opened, incumbent distribution partners may face new competitive pressure, while technology suppliers could gain opportunities to serve multiple licensees. Where a ruling triggers legislative reform, the timeline is likely to be measured in years, so the one-year review period is a minimum rather than a forecast.",
  "Our assessment is that the extension reflects administrative caution rather than a view on the merits. Stakeholders should follow the Council of State docket, review the reasoning for any competition-law findings and engage early with the legislator. Dutch regulatory teams such as Kalff Katz and Franssen, Stibbe and AKD can advise on both challenge strategies and licensing readiness if the market opens."
 ]
},
{
 "slug": "us-appeals-court-state-authority-sports-prediction-markets-september-2026-operator-playbook",
 "title": "US Appeals Court Backs State Oversight of Prediction Markets",
 "category": "Regulatory",
 "excerpt": "A 25 September ruling reportedly lets states regulate sports event contracts. Supreme Court review looks likely and operators need a playbook.",
 "publish_date": "2026-10-02T09:15:00Z",
 "related_jurisdictions": ["united-states", "canada", "australia"],
 "related_firms": ["greenberg-traurig-llp", "covington-and-burling-llp", "holland-and-knight-llp"],
 "body": [
  "On 25 September 2026, major outlets reported that a US federal appeals court ruled that states can regulate sports prediction markets operated by platforms such as Kalshi, adding to a run of rulings that have gone against the platforms. Separate commentary describes a set of certiorari petitions across two circuits and roughly twenty states that is bringing the issue to the Supreme Court. We could not access the full opinion for this note, so the analysis below is limited to the headline holding and to the structure of the dispute.",
  "The core legal question has not changed. Platforms argue that sports event contracts are swaps traded on a federally designated contract market, so that the Commodity Exchange Act gives the Commodity Futures Trading Commission exclusive jurisdiction and pre-empts state gaming law. States answer that these products are bets on sporting events, that the statute preserves their traditional police power over gambling, and that a federal registration does not authorise conduct that a state prohibits. Courts that have sided with the states have generally accepted the second framing, at least at the preliminary stage.",
  "The outcome matters well beyond the platforms. Licensed sportsbooks pay high taxes, comply with integrity, safer-gambling and anti-money-laundering rules, and operate through state licences. A product that offers economically similar exposure without those obligations creates a competitive asymmetry, which is why many state regulators and licensed operators have supported enforcement. Conversely, if pre-emption prevails, state licensing of sports wagering could be weakened for any product that can be structured as an event contract.",
  "A split of authority between circuits is the classic ground for Supreme Court review, and the number of states involved increases the stakes. Even if certiorari is granted, a decision would not arrive until the following term, so the market will operate under mixed rules for many months. Cease-and-desist orders, injunctions and geofencing obligations may vary by state, and the platforms may continue to offer contracts in states where they have not been restrained while challenging orders elsewhere.",
  "Operators and investors should build a playbook around three questions. First, in which states does the business hold a gaming licence, and does any prediction-market activity, such as partnerships, data licensing or marketing, risk breaching licence conditions? Second, are there counterparty exposures to a platform that could face an injunction, including payment, clearing and distribution agreements? Third, how would a pre-emption win or loss alter product strategy, tax planning and lobbying positions?",
  "Regulators in other jurisdictions are watching. European authorities have been cooperating on action against unlicensed prediction products, and the Canadian and Australian debates about whether event contracts are gambling will draw on the US reasoning. For international groups that operate in the United States through partnerships or investments, the risk of inconsistent legal positions across markets suggests careful governance and consistent public messaging.",
  "In the short term, compliance teams should document each state's position, track orders and keep contingency plans for withdrawing products or geofencing. US gaming and financial regulatory teams at firms such as Greenberg Traurig, Covington and Holland and Knight are well placed to advise on the interplay between federal commodities law and state gaming statutes."
 ]
},
{
 "slug": "uk-machine-games-duty-doubling-speculation-autumn-budget-betting-shops-2026",
 "title": "UK Machine Games Duty Doubling: Planning for the Budget",
 "category": "Tax",
 "excerpt": "Speculation points to higher Machine Games Duty rates at the Autumn Budget. Retail betting operators should model the downside now.",
 "publish_date": "2026-10-02T10:00:00Z",
 "related_jurisdictions": ["united-kingdom", "ireland", "gibraltar"],
 "related_firms": ["wiggin-llp", "harris-hagan", "pinsent-masons-llp"],
 "body": [
  "Industry commentary on 25 September 2026 reported speculation that the UK government may announce a sharp increase in Machine Games Duty at the forthcoming Autumn Budget, with the lower rate rising from 5 per cent to 10 per cent, the middle rate from 20 per cent to 40 per cent and the higher rate from 25 per cent to 50 per cent. These figures are speculation, not government policy, and no announcement has been made. Nevertheless, the discussion is a reminder that tax is now the primary lever of UK gambling policy and that operators should plan for several outcomes.",
  "Machine Games Duty applies to the net takings from gaming machines, including the fixed-odds betting terminals that remain an important part of retail betting profitability. Because the duty is charged on takings rather than profit, a higher rate has a direct and immediate effect on margin. Retail operators have already faced closures, and commentary from the sector suggests that many shops could become unviable if the duty were doubled, with consequential effects on jobs, sponsorship funding and high-street presence.",
  "The wider tax context heightens the risk. Remote gaming duty has been set at 40 per cent, a new remote betting duty is scheduled for 2027, and the statutory gambling levy is being collected alongside higher Gambling Commission fees from 1 October 2026. The Betting and Gaming Council has argued that the cumulative burden pushes customers toward the unlicensed market. The Treasury, by contrast, has treated gambling as a source of revenue and points to the need to fund public services and regulatory costs.",
  "For operators, the first step is financial modelling. Companies should estimate profit and loss by shop and by machine under the speculated rates and under lower alternatives, and identify the thresholds at which closure is rational. Models should include the interaction with business rates, wage costs and the statutory levy. Where lease obligations are long, break clauses and landlord negotiations should be reviewed early, because a budget announcement can quickly change the bargaining position.",
  "The second step is legal review of contractual and licensing consequences. Closing premises triggers duties under the premises licence and the Gambling Commission's licence conditions, including notification requirements, and may affect arrangements with franchisors, machine suppliers and betting-office licence holders. Employment law processes for collective redundancy should be considered where numbers are significant. Finance agreements may contain covenants linked to EBITDA that a tax change could breach.",
  "The third step is engagement. Responses to consultation and pre-budget representations are most effective when they are grounded in data about employment, tax yield and the likely migration of play. The government has proposals open on other parts of the regime, and the Commission is working on burden reduction, so evidence can be cross-referenced. Operators outside Great Britain, including in Ireland and Gibraltar, should also assess the effect on group cash flows and transfer pricing.",
  "Until the Budget is delivered, nothing is certain. A cautious approach is to prepare scenarios, avoid irreversible commitments where possible and keep stakeholders informed. UK regulatory and tax advisers such as Wiggin, Harris Hagan and Pinsent Masons can assist with planning, representations and implementation if the changes are confirmed."
 ]
},
]

m.ARTICLES = ARTICLES
if __name__ == "__main__":
    for a in ARTICLES:
        print(len(a["title"]), len(a["excerpt"]), len(a["body"]), a["slug"])
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_02oct.bak")
        m.patch(p)
    print("done")
