#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-02 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))

ARTICLES = [
{
 "slug": "ukgc-customer-funds-protection-ratings-reform-2026",
 "title": "UKGC reopens the customer funds ratings regime",
 "category": "Compliance",
 "excerpt": "An informal consultation on the protection of customer funds rating system puts insolvency disclosure back in play for remote licensees.",
 "publish_date": "2026-09-02T07:30:00Z",
 "related_jurisdictions": ["united-kingdom", "gibraltar", "malta"],
 "related_firms": ["harris-hagan", "wiggin-llp", "joelson-llp", "northridge-law-llp"],
 "body": [
  "The Gambling Commission has opened an informal consultation on amendments to the protection of customer funds rating system, a piece of the regulatory architecture that most licensees treat as settled and few revisit. Licence condition 4.2.1 requires operators holding customer funds to disclose their arrangements for protecting those funds in the event of insolvency, the level of protection achieved and the method by which it is achieved, expressed through a three-tier rating of not protected, medium protection or high protection. The rating is a disclosure obligation rather than a prudential one, and that distinction is the source of most of the difficulty the Commission is now trying to address.",
  "The regime as drafted does not require any operator to protect customer funds at all. It requires the operator to tell customers, accurately, whether it does. An operator holding player balances in its general trading account, exposed in full to unsecured creditors on a winding up, complies with the condition by rating itself not protected and saying so. Since 31 October 2025 such an operator must also remind each affected customer every six months that their funds are unprotected. The theory is that disclosure disciplines behaviour through customer choice. The evidence that customers read, understand or act on the rating has never been strong.",
  "Where the framework produces genuine legal risk is at the boundary between the medium and high tiers. High protection generally contemplates funds held in a trust arrangement, or an equivalent structure, under which the customer has a proprietary claim that survives the operator's insolvency. Medium protection covers arrangements such as segregated accounts with an insolvency practitioner arrangement or a third party guarantee, where the customer's position is better than that of an ordinary unsecured creditor but falls short of a beneficial interest. The gap between a segregated account and a valid trust is a matter of English trust law rather than gambling regulation, and it turns on certainty of intention, certainty of subject matter and certainty of objects rather than on the label the operator applies to the bank account.",
  "That is precisely where self assessments go wrong. Operators routinely rate themselves high protection on the strength of a designated client account, a policy statement in the terms and conditions and an internal instruction that the balance is not to be used for working capital. None of that necessarily creates a trust. If the operator retains an unfettered ability to draw on the account, if balances are commingled with corporate funds at any point in the payment chain, or if the constitutive documentation was never drafted with declaratory intent, a court asked to characterise the arrangement on insolvency may well find a debt rather than a trust. The customers would then discover the true position at the worst possible moment, and the operator would have made a false statement to its customers for however long the rating stood.",
  "A misstated rating is not a technical breach. It engages the disclosure obligation in licence condition 4.2.1 directly, it is capable of amounting to a misleading commercial practice under consumer protection law, and it is exactly the kind of failure the Commission has shown willingness to treat as evidence going to suitability rather than as an isolated lapse. British gambling regulatory practices, including Harris Hagan, Wiggin LLP, Joelson LLP and Northridge Law LLP, have long advised that the rating should be supported by a written legal opinion on the characterisation of the arrangement, refreshed when the banking structure or the group's payment flows change. Most operators do not hold one.",
  "The consultation should also be read against the Commission's wider financial resilience work. The regulator has become markedly more interested in the balance sheet position of its licensees, in the adequacy of their funding arrangements and in what happens to customers when an operator fails, and it has the enforcement history to justify the interest. Where a regulator is simultaneously reviewing a disclosure regime and scrutinising financial soundness, the plausible direction of travel is toward tightening the definitional boundaries between tiers, requiring better evidence for a claimed rating, and improving the prominence and comprehensibility of the disclosure to customers. Operators lobbying only to preserve the status quo are unlikely to find that a persuasive submission.",
  "The practical preparation is straightforward and worth doing whether or not the rules change. Licensees should establish where customer funds physically sit at every point between deposit and withdrawal, including balances resting with payment service providers, and identify whether any part of the chain commingles. They should locate the document said to create the protection, read it against the legal test rather than against the intention behind it, and confirm that the person who last assessed the rating had the standing to do so. They should check that the six monthly reminder is actually being sent to the right population, and that the rating disclosed to customers matches the rating recorded with the Commission.",
  "The wider lesson is that dormant licence conditions do not stay dormant. Condition 4.2.1 has generated little enforcement activity, which has allowed a broad range of assessment practice to develop without correction. A consultation is the moment that latitude closes. Operators that discover a mischaracterisation now can restructure the arrangement, correct the disclosure and document the remediation on their own timetable. Operators that wait for the amended rules will be correcting a rating that the regulator has already asked them to justify."
 ]
},
{
 "slug": "germany-gluecksspielstaatsvertrag-statutory-review-2026",
 "title": "Germany's gambling treaty faces its first real review",
 "category": "Regulatory",
 "excerpt": "The statutory evaluation of GlueStV 2021 opens the framework itself, not merely its rules, to revision for the first time since 2021.",
 "publish_date": "2026-09-02T08:20:00Z",
 "related_jurisdictions": ["germany", "austria", "malta", "netherlands"],
 "related_firms": ["hambach-and-hambach", "redeker-sellner-dahs", "cms-germany", "bird-and-bird"],
 "body": [
  "The Gemeinsame Gluecksspielbehoerde der Laender is preparing for the statutory review of the Interstate Treaty on Gambling, the first comprehensive assessment of the framework since it took effect in 2021. The Treaty contains its own evaluation clause, which means this is not a discretionary policy exercise the states may quietly defer. It is a built in obligation to test whether the regime has achieved its stated objectives, and it arrives at a moment when the evidence on those objectives is uncomfortable for the framework's designers.",
  "The Treaty's aims are set out in section 1 and are cumulative rather than ranked: preventing gambling addiction, channelling demand into ordered and supervised paths, protecting minors and players, and ensuring integrity in the conduct of gambling. A review measured against those aims has to confront the channelisation data directly. A study commissioned by the GGL estimated that licensed operators captured just over seventy seven percent of German online gambling spending in 2024, leaving unregulated providers with close to twenty three percent, equivalent to roughly 547 million euros. A framework whose central justification is channelling demand into supervised paths, and which leaks a quarter of that demand, has an evidential problem that no amount of enforcement reporting resolves.",
  "The legally interesting question is what the states can do about it. The Treaty is an agreement among the sixteen Laender, and material amendment requires their collective assent through domestic ratification. That is why the framework has been so difficult to adjust in operation, and why the GGL has been forced to work at the margins through administrative measures such as the tiered stake structure introduced in July 2026 rather than through structural change. The review creates a formal occasion at which structural change can be tabled, but it does not resolve the underlying coordination problem. A single state's objection is capable of holding the position.",
  "Berlin's assumption of the coordinating role in German gambling oversight sharpens rather than settles this. Institutional leadership shapes the agenda, the framing of the evidence and the questions the review asks, but it does not confer the power to bind other states on substance. Operators reading the review as a reliable route to liberalisation should temper the expectation. German gaming counsel, including Hambach and Hambach, Redeker Sellner Dahs and CMS Germany, have consistently advised that predictions about German gambling reform should be discounted heavily for the federal ratification mechanism, and nothing about the current cycle changes that arithmetic.",
  "There is also a European overlay the review cannot ignore. The compatibility of individual restrictions with the freedom to provide services under Article 56 of the Treaty on the Functioning of the European Union depends on those restrictions being suitable and necessary to achieve the public interest objectives claimed for them, applied consistently and systematically. Where a regulator's own commissioned research shows a restriction is not achieving the channelling objective it was justified by, the coherence of the justification weakens. That will not by itself invalidate the German regime, and the Court of Justice has historically afforded member states wide latitude in gambling policy. It does mean the state's evidential position in future proceedings is influenced by what this review records.",
  "For operators, the immediate value of the review is informational rather than transactional. What the GGL chooses to measure, and how it frames the shortfall between the licensed and unlicensed markets, will signal the supervisory priorities for the remainder of the Treaty period. If the review attributes the channelisation gap principally to product restrictions, the regulatory response points toward further calibrated relaxation of the kind the stake tiering represents. If it attributes the gap principally to inadequate enforcement against offshore supply, the response points toward payment blocking, IP blocking and supplier liability, all of which fall on licensed intermediaries as much as on offshore operators.",
  "Licensees should participate in the evidence gathering rather than await the outcome. Regulators conducting statutory reviews are unusually receptive to structured operational data, and licensed operators hold the material that most directly bears on the question: the acquisition costs of competing against untaxed supply, the observed player migration when a limit binds, the conversion loss at each verification step, and the proportion of returning players who arrive from offshore brands. That evidence is more persuasive than assertions about competitiveness, and it is currently absent from a debate conducted largely on survey data.",
  "The realistic expectation for the review's outcome is incremental adjustment within the existing structure rather than a reconstituted framework. Deposit limit mechanics, the operation of the LUGAS monitoring system, advertising rules and the treatment of table games are all candidates for revision without reopening the Treaty's architecture. Operators building German business cases should assume the current architecture persists through the review period, that the specific parameters within it remain in motion, and that the capacity to reconfigure product and compliance systems quickly is worth more in Germany than a settled view of where the rules will land."
 ]
},
{
 "slug": "italy-adm-land-based-concession-tender-2026",
 "title": "Italy's land-based tender reshapes retail gambling",
 "category": "Market Entry",
 "excerpt": "A tender covering roughly 10,000 betting shops and hundreds of thousands of machines, with investment expected above 1.5 billion euros.",
 "publish_date": "2026-09-02T09:10:00Z",
 "related_jurisdictions": ["italy", "malta", "united-kingdom"],
 "related_firms": ["dla-piper-italy", "studio-legale-sbordoni-and-partners", "cms-italy", "norton-rose-fulbright-italy"],
 "body": [
  "The Agenzia delle Dogane e dei Monopoli's land-based concession tender is the largest structural reform of Italian retail gambling in more than a decade. It redistributes concessions covering roughly 10,000 betting points and several hundred thousand gaming machines, with total investment expected to exceed 1.5 billion euros. Coming after the online tender that closed in 2025 with a 7 million euro licence fee and 46 approved applications, it completes a reorganisation of the Italian market in which both channels are re-tendered under materially heavier financial terms within roughly eighteen months of each other.",
  "The defining feature of the retail tender, and the one that distinguishes it from the online process, is that spatial planning is decided by parties other than the concession holder. The April 2026 meeting between the Ministry of Economy and Finance and representatives of local municipalities to define the spatial planning framework was not an administrative formality. Italian municipalities and regions have for years imposed distance requirements keeping gambling venues away from schools, places of worship, hospitals and other sensitive sites, and the resulting patchwork has been the single largest source of litigation in Italian land-based gambling. A concession awarded nationally is exercised locally, and the local rules can render a licensed location unusable.",
  "Bidders therefore have to price a right whose exercisability is not fully within the awarding authority's gift. The pattern established through years of administrative litigation is instructive: national concessions and local siting restrictions have coexisted, with the administrative courts generally upholding municipal competence to regulate location on public health grounds while requiring proportionality and, in some cases, transitional protection for existing venues. A bidder that models revenue on a full complement of operating points, without discounting for locations that cannot lawfully open or renew where they stand, is modelling a business that does not exist.",
  "The valuation problem is compounded by the concession term and by what happens at its end. Italian gambling concessions carry defined terms, technical and reporting obligations, and provisions governing the treatment of assets and, in some structures, continuity of operation on expiry. The economics of a 1.5 billion euro investment depend heavily on the length of the term, the security of tenure within it, and whether the incumbent enjoys any advantage at re-tender. Bidders should assume no informal expectation of renewal survives a competitive re-tender, and should recover their investment within the term rather than on the assumption of a second one.",
  "There is a corporate structuring dimension that international groups consistently underestimate. Italian concessions are held by Italian entities subject to Italian technical certification, reporting and integrity requirements, and the concession holder's suitability extends up the ownership chain. Groups entering through acquisition rather than direct bid inherit the target's regulatory history, its outstanding disputes with ADM, its relationships with the point-of-sale network and any pending administrative proceedings. Italian gambling practices, including DLA Piper Italy, Studio Legale Sbordoni and Partners, CMS Italy and Norton Rose Fulbright Italy, have advised that due diligence on Italian retail targets should extend to the municipal position of each material location, which is slow work and is frequently compressed into a timetable that cannot accommodate it.",
  "The fiscal terms complete the picture and should be assessed together with the tender price rather than after it. The online concessions carry gross gaming revenue taxation of 24.5 percent for sports betting and 25.5 percent for casino, alongside an annual fee of 3 percent of GGR on top of the 7 million euro entry fee. Retail gambling in Italy carries its own duties, which differ by product and have been adjusted repeatedly in successive budget laws. A bidder's model needs to survive a rate increase, because the recent history of Italian gambling taxation offers no basis for assuming stability across a full concession term.",
  "Strategically, the tender will concentrate the market. The combination of a substantial upfront commitment, a national footprint requirement and heavy compliance obligations favours large, well capitalised groups and disadvantages the independent operators who have historically held much of the Italian retail network. That is the same dynamic the online tender produced, where the fee structure delivered a market dominated by international groups and domestic incumbents with the balance sheet to pay it. Smaller operators facing the retail tender should be considering consortium bids, sale to a bidder that needs their locations, or an orderly exit, and should be doing so before the tender timetable removes the option.",
  "For groups with Italian ambitions the practical sequence matters more than the strategic case. Location level regulatory diligence should begin before the bid economics are fixed rather than after, because it determines them. The corporate vehicle and its ownership chain should be structured to satisfy ADM suitability requirements from the outset, since restructuring during an evaluation is disruptive and invites scrutiny. And the model should be stress tested against a materially reduced network of operable locations, which is the most likely outcome and the one that most bids will not have priced."
 ]
},
{
 "slug": "malta-mga-betting-integrity-athlete-esports-reviews-2026",
 "title": "MGA turns integrity reviews on athletes and esports",
 "category": "Enforcement",
 "excerpt": "Malta's supervisory programme targets athletes betting on their own sport and integrity risk in esports markets, with thematic reviews to follow.",
 "publish_date": "2026-09-02T10:00:00Z",
 "related_jurisdictions": ["malta", "united-kingdom", "gibraltar", "sweden"],
 "related_firms": ["camilleri-preziosi", "wh-partners", "gvzh-advocates", "ellul-and-co"],
 "body": [
  "The Malta Gaming Authority's supervisory engagement programme for 2026 places sports betting integrity alongside compliance and player protection at the centre of its work, with focused reviews examining the risk of athletes betting on their own sport and integrity concerns in esports markets. For a jurisdiction that licenses a substantial share of Europe's business to business supply and a large volume of business to consumer operators, a thematic integrity review is a market wide event rather than an operator specific one. The findings will set expectations for licensees who were never inspected.",
  "Athlete betting is a harder compliance problem than its framing suggests. The prohibition is generally imposed by the sport's own governing body rather than by gambling regulation, which means the operator's obligation is not to enforce a rule binding on it but to prevent and detect account activity that breaches somebody else's rule. Doing so requires identifying which of an operator's customers are participants in a given competition, which is information the operator does not hold and cannot readily obtain. Name matching against squad lists is unreliable at scale, produces false positives that create their own customer treatment problems, and fails entirely where the account is held by a proxy, which is how the conduct usually presents.",
  "That is why proxy betting rather than direct participant betting is where supervisory attention should be expected to concentrate. An athlete betting in their own name is an unsophisticated case that existing controls catch. The realistic pattern involves an associate's account, funded from a source connected to the athlete, showing unusual specificity of market selection and timing. Detecting it requires linking accounts by device, payment instrument, address and behavioural pattern, and then interrogating the resulting cluster against event level data. Operators that have invested in account linking for anti-money laundering purposes already hold most of the capability. Very few have applied it to integrity.",
  "The esports limb raises different and in some respects more difficult questions. Esports competition is fragmented across titles, publishers and tournament organisers, with governance ranging from mature structures to none, and with participants who are frequently young and not subject to any enforceable integrity code. Lower tier events with minimal prize money attract disproportionate suspicious betting activity precisely because the cost of corrupting a participant is low. An operator that offers markets on such events without regard to the governance standard of the organiser is assuming an integrity risk that its market selection created, and the MGA's interest in the area indicates it regards that as a licensee decision rather than an inherent feature of the product.",
  "The consequence is that market selection is becoming a supervised compliance function. Whether to offer markets on a particular competition, at which tiers, in which markets and to what limits, has traditionally been a trading judgement made on liquidity and margin. A regulator asking what integrity assessment supported the decision to offer that market converts it into a documented risk decision. Maltese gaming practices, including Camilleri Preziosi, WH Partners and GVZH Advocates, have been advising licensees that the defensible position requires a written framework for market approval, with assessment criteria covering the governance of the organiser, the availability of integrity monitoring, the participant age profile and the prize structure relative to corruption incentive.",
  "Data sharing sits underneath all of this and remains legally awkward. Effective integrity work depends on operators sharing suspicious activity with each other, with monitoring bodies and with sports governing bodies, and that involves disclosing personal data about identified customers to third parties, frequently across borders, generally without consent and often where the customer has done nothing that has yet been established as wrongdoing. The lawful basis is usually legitimate interests or a legal obligation depending on the jurisdiction and the recipient, and the analysis is genuinely difficult. Operators that share reflexively and operators that refuse to share at all are both exposed, the first under data protection law and the second to a regulator that regards participation in integrity networks as an expectation.",
  "Licensees should also anticipate how a thematic review is conducted and what it produces. The MGA's stated approach is risk based, evidence led and outcomes focused, which in practice means requesting comparable material from a defined population of licensees, identifying the distribution of practice, and publishing findings that establish a standard by reference to what better operators were already doing. Licensees at the weaker end of the distribution learn their position from a published document describing the sector. The time to establish where the operator sits is before the information request, not after it.",
  "The practical preparation is a short list. Operators should be able to demonstrate a documented market approval framework and evidence that it was applied; an account linking capability extended from financial crime to integrity purposes; a defined escalation path for suspicious activity with recorded decisions and timeframes; membership of or engagement with an integrity monitoring body; and a data protection assessment supporting the sharing the operator actually does. None is expensive to build in advance. Each is difficult to reconstruct once a supervisory request has fixed the record."
 ]
},
{
 "slug": "eu-one-percent-gambling-levy-own-resource-2026",
 "title": "Brussels weighs an EU-wide levy on gambling revenue",
 "category": "Tax",
 "excerpt": "A proposed EU own resource on gambling revenue would add a supranational layer above national duties that are already rising sharply.",
 "publish_date": "2026-09-02T10:50:00Z",
 "related_jurisdictions": ["malta", "netherlands", "sweden", "italy", "germany"],
 "related_firms": ["camilleri-preziosi", "wh-partners", "bird-and-bird", "cms"],
 "body": [
  "A proposal to make gambling revenue an own resource of the European Union budget has moved from a backbench idea to a live item in the Brussels fiscal debate. Tabled in February 2026 by Romanian MEP Victor Negrescu, a vice president of the European Parliament, the original formulation contemplated a levy of one percent of gambling gross revenue across all twenty seven member states. The European Commission's May 2026 estimate that a three percent levy on net turnover of the online gambling sector would raise roughly 1.9 billion euros annually between 2028 and 2034, as part of a package of digital, gambling and crypto measures worth up to 11 billion euros a year, indicates the concept is being modelled seriously at Commission level rather than merely entertained.",
  "The legal obstacle is more significant than the political one, and operators should understand its shape before assessing the risk. Own resources are established under Article 311 of the Treaty on the Functioning of the European Union, which requires a Council decision adopted unanimously after consulting the European Parliament, and then approval by every member state in accordance with its own constitutional requirements. Unanimity plus twenty seven national ratifications is the most demanding procedure in the Union's fiscal toolkit. Malta, where gambling accounts for close to a tenth of gross domestic product and whose Prime Minister has insisted that fiscal sovereignty remain with member states, has both a clear incentive and an unambiguous legal ability to stop it.",
  "That should not lead operators to dismiss the proposal, for two reasons. First, proposals of this kind frequently survive in altered form. A measure blocked as an own resource can reappear as a harmonisation directive under a different legal basis, as a coordinated commitment outside the Treaty framework, or as a template that member states adopt nationally because the modelling work has already been done for them. Second, the exercise itself has an effect independent of its outcome, because it establishes a Commission level view of what the European online gambling sector earns and what proportion of that can be extracted without collapsing the base.",
  "The base definition is where the practical exposure sits and where the industry's technical input matters most. A levy on gross gaming revenue, on net turnover, or on stakes produces radically different burdens on the same business, and the difference is largest for high frequency, low margin products where turnover vastly exceeds revenue. The Commission's reference to net turnover rather than gross gaming revenue is not a drafting nicety. Operators and their advisers should be engaging on definitional questions now, because base definitions adopted at the modelling stage tend to persist into legislative text long after the headline rate has been negotiated.",
  "The cumulative burden argument is the industry's strongest and is being made poorly. European online gambling tax rates rose in six markets between 2024 and 2026: Sweden to twenty two percent, Romania to twenty seven percent, the Netherlands to 37.8 percent, the United Kingdom to forty percent, Italy into the restructured 24.5 and 25.5 percent concession regime, and France under successive finance law levies. Layering a supranational charge on top of national rates at those levels is a different proposition from introducing it into a lightly taxed sector. The European Gaming and Betting Association has called the levy unworkable, which is an assertion rather than an argument. The persuasive version is quantitative: the point at which the combined burden pushes marginal players toward unlicensed supply, evidenced by channelisation data from markets that have already tested it.",
  "That evidence exists and is unusually good. Germany's own commissioned research put unlicensed activity at close to twenty three percent of online spending, and the relationship between fiscal and regulatory burden and channelisation has been examined repeatedly across the Nordic and Dutch markets. An argument that a levy would reduce the taxable base by driving players offshore is one that finance ministries take seriously, because it goes to revenue rather than to industry margin. Malta focused practices, including Camilleri Preziosi and WH Partners, together with pan European firms such as Bird and Bird and CMS, are best placed to assemble that case across jurisdictions, and the submission window is the modelling phase rather than the legislative one.",
  "Operators should also consider the collection mechanics, which are frequently where a proposal founders or where its real cost lies. Gambling taxation in Europe is administered nationally, with widely divergent definitions of taxable revenue, differing treatment of bonuses and free bets, and no common reporting standard. A supranational levy requires either a parallel reporting obligation, which imposes cost on every licensee in the Union, or reliance on national administrations to collect and remit on a harmonised base they do not currently maintain. Neither is trivial, and the compliance cost of the first would fall on operators regardless of the rate ultimately set.",
  "For planning purposes, the sensible position is that adoption as an own resource within the current multiannual financial framework negotiation is improbable given the unanimity requirement and Malta's declared position, while the idea itself is unlikely to disappear. Groups building European models through 2030 should treat a supranational or coordinated additional charge as a low probability but high impact scenario, should ensure their reporting systems can produce revenue data on more than one base definition, and should participate in the technical consultation now rather than waiting for a legislative proposal that would arrive with its definitions already fixed."
 ]
},
]

AUTHOR = "GamblingLawyers.com Editorial Team"


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,author:%s,author_slug:"",'
        'publish_date:%s,related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]), esc(a["title"]), esc(a["category"]), esc(a["excerpt"]),
            esc(AUTHOR), esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_02sep.bak")
        patch(p)
    print("done")
