#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert 5 articles dated 2026-09-22 into _source.html and app.js."""
import json, re, shutil, sys, os

BASE = os.path.dirname(os.path.abspath(__file__))
AUTHOR = "GamblingLawyers.com Editorial Team"

ARTICLES = [
{
 "slug": "uk-gambling-commission-deposit-limit-phase-two-deadline-30-september-2026",
 "title": "Deposit Limit Deadline Lands on 30 September",
 "category": "Compliance",
 "excerpt": "The second phase of the UKGC deposit limit rules bites this month after a three-month extension. There is no third reprieve.",
 "publish_date": "2026-09-22T07:30:00Z",
 "related_jurisdictions": ["united-kingdom", "ireland", "malta"],
 "related_firms": ["harris-hagan", "wiggin-llp", "mishcon-de-reya-llp", "pinsent-masons-llp", "joelson-llp"],
 "body": [
  "The second phase of the Gambling Commission's updated deposit limit requirements takes effect on 30 September 2026, following an extension of three months from the original 30 June date granted after operators reported that the build was more demanding than anticipated. That extension has now been consumed. Licensees who treated the additional quarter as breathing room rather than as a compressed delivery window are approaching the end of the month with a remote customer base that must be prompted, a data model that must support the prompt and an audit trail that must survive examination, and they are doing so with no expectation of a further concession.",
  "The substance of the phase two obligation is easily stated and awkward to build. Remote licensees must give customers the ability to set a deposit limit at registration, must present that option in a way that does not steer the customer away from using it, and must periodically invite customers with a limit in place to review it. The regulatory theory is that a limit set once and never revisited decays in value as a control, because the customer's circumstances change while the number does not. The engineering consequence is that the operator must track, per customer, when a limit was set, when it was last reviewed, what the outcome of the review was and when the next prompt falls due. Very few legacy platforms were designed to hold that state.",
  "The failure mode the Commission is most likely to find is the silently skipped prompt. A review invitation that is generated but suppressed by a marketing preference flag, a prompt that fires into a session the customer has already abandoned, a customer segment excluded from the prompt logic by an inherited configuration that nobody has read since it was written: each of these produces a population of customers who were never asked. Practitioners at Harris Hagan, Wiggin LLP, Mishcon de Reya LLP, Pinsent Masons LLP and Joelson LLP have been pressing clients to test the negative case rather than the positive one, on the basis that demonstrating a prompt works for a customer chosen at random proves very little about the customers the logic never reached.",
  "There is a design question underneath the compliance question that operators are handling with widely varying degrees of rigour. The requirement that the option be presented neutrally imports a body of thinking about choice architecture that British gambling regulation has previously touched only lightly. A deposit limit field that is technically present but placed below the fold, pre-populated with a high default, styled as secondary to the deposit button, or preceded by copy framing limits as an obstacle to play, satisfies the letter of a presence requirement and defeats its purpose. Regulators elsewhere in Europe have begun to examine interface design directly, and an operator whose limit journey converts at a rate conspicuously below the market should expect to be asked why.",
  "The interaction with the financial risk assessment framework compounds the exposure rather than sitting alongside it. An operator that holds a customer-set deposit limit, and separately holds the outputs of a risk assessment, and separately holds transaction data showing behaviour inconsistent with both, is holding the components of a finding it has not made. The Commission's enforcement reports have repeatedly identified operators possessing the data needed to identify a problem while lacking any process that brought the data together. A limit that is repeatedly raised on request, by a customer whose risk indicators are also rising, is precisely the pattern that an integrated review would surface and that siloed systems will not.",
  "Group operators running multiple brands on shared infrastructure face an additional and frequently underestimated problem. A customer-set limit that binds at brand level, while the customer holds accounts across three brands in the same group, produces an aggregate exposure that no individual limit constrains. The regulatory position on cross-brand aggregation is not as fully articulated in Britain as it is becoming in Spain, where the regulator has been developing a cross-operator limit architecture, but the direction of travel is unmistakable. An operator whose limit design assumes brand isolation is building to a standard that is already being overtaken.",
  "The evidential preparation matters as much as the build, because the question at the point of examination will not be whether the operator implemented the requirement but whether it can show that it did. That means retaining, for each customer, the prompt events generated, the prompt events delivered, the customer response and the resulting limit state, in a form that can be queried by date range and customer segment. It also means being able to identify and explain any customer population that received no prompt. An operator that can produce a policy document and a screenshot has prepared for the wrong question.",
  "The remaining days are sufficient for verification but not for construction, and licensees should allocate them accordingly. Run a reconciliation between the total remote customer base and the population the prompt logic actually reached, and investigate every exclusion. Test the registration journey on mobile as well as desktop, since the presentation problem is most acute where screen space is scarcest. Confirm that limit changes are logged with a timestamp and an actor. Where a gap is found that cannot be closed by 30 September, record it, quantify it and prepare a remediation plan, because a licensee that identifies and reports its own shortfall occupies a materially better position than one that waits to be told."
 ]
},
{
 "slug": "brazil-spa-ordinance-2750-payment-flow-controls-illegal-gambling-2026",
 "title": "Brazil Targets the Money Behind Illegal Betting",
 "category": "Enforcement",
 "excerpt": "Ordinance SPA/MF 2,750/2026 turns payment institutions into the front line against unlicensed operators serving Brazilian players.",
 "publish_date": "2026-09-22T08:15:00Z",
 "related_jurisdictions": ["brazil", "colombia", "peru"],
 "related_firms": ["pinheiro-neto-advogados", "mattos-filho"],
 "body": [
  "The Secretariat of Prizes and Betting has published Ordinance SPA/MF No. 2,750/2026, establishing procedures directed at the financial flows that sustain illegal gambling supply in Brazil. The instrument reflects a conclusion that regulators across several continents have reached in sequence: that domain blocking degrades quickly against a determined operator, and that the payment layer is the point in the chain where interdiction is both technically durable and commercially decisive. An unlicensed operator can register a new domain within hours. It cannot replace settlement and payout capability at the same speed.",
  "The Brazilian context gives this approach unusual force because of the payment infrastructure itself. Pix, the instant payment system operated by the central bank, is the dominant deposit and withdrawal rail for Brazilian gambling customers, and it is a domestic, account-based, centrally operated system rather than a network of international card schemes. That architecture means there is a defined and identifiable set of regulated participants through which essentially all relevant value moves. A measure that obliges those participants to identify and disrupt transactions connected to unlicensed operators is therefore addressed to a manageable number of supervised entities rather than to a diffuse global payments landscape.",
  "For licensed operators, the immediate consequence is not relief but scrutiny. A regime that traces gambling-related financial flows necessarily traces licensed flows as well, and the supervisory apparatus built to identify unlicensed activity is the same apparatus that will observe irregularities in licensed activity. Operators whose payment arrangements involve intermediaries, aggregators, or accounts held other than in the licensed entity's own name should reconsider those structures now. Counsel at Pinheiro Neto Advogados and Mattos Filho have been advising clients that structural payment opacity, however historically convenient, is becoming the single most dangerous feature of a Brazilian operation.",
  "The compliance burden for payment institutions raises questions that the ordinance can specify but not fully solve. Identifying a transaction as gambling-related requires either merchant categorisation that the recipient controls or behavioural inference that the institution must construct, and both produce error. A false positive blocks a lawful transaction and exposes the institution to customer complaint; a false negative leaves an unlicensed flow intact and exposes it to regulatory criticism. Institutions will calibrate that trade-off according to where they perceive the greater risk, and experience elsewhere suggests they calibrate conservatively, which means licensed operators with atypical payment patterns will encounter friction they did not cause.",
  "There is a regional dimension that Brazilian developments now routinely acquire. Colombia's Coljuegos has operated payment and access blocking for years and has extended its value added tax treatment of online gambling on a permanent basis, and Peru's regime has incorporated payment channel obligations from the outset. What is emerging across Latin America is a common enforcement template in which licensing, payment interdiction and access blocking operate as three coordinated instruments rather than as alternatives. Operators planning multi-market entry in the region should assume that the payment compliance work done for Brazil is substantially reusable and that the analysis is converging rather than diverging.",
  "The timing relative to Brazil's licensing calendar is significant. With a second authorisation window anticipated and the regulator having consulted during the northern summer on revised authorisation requirements, the market is approaching a moment at which the population of licensed operators expands. A regulator that intends to admit more licensees has a strong institutional reason to demonstrate, before doing so, that the illegal market is being suppressed. The payment measures are therefore best understood as preparatory rather than reactive, and applicants should expect the authorisation assessment to include questions about their own payment governance that would not have been asked in the first window.",
  "For affiliates, payment processors and technology suppliers serving the Brazilian market, the analysis is one of counterparty exposure rather than direct regulation. A supplier whose client list includes operators without Brazilian authorisation, while also including licensed operators, is carrying a contamination risk that will be assessed by banks, by the regulator and by prospective licensed partners. The practical response is a documented client screening process that verifies authorisation status at onboarding and re-verifies it periodically, together with contractual termination rights that can be exercised without extended notice. Suppliers who cannot demonstrate that process are likely to find licensed operators declining to contract with them.",
  "The near-term action list for licensed operators is concrete. Map every payment flow into and out of the Brazilian operation and identify the legal entity that holds each account. Eliminate intermediary structures that cannot be justified on operational grounds capable of being explained to a regulator. Confirm that customer withdrawal destinations are subject to name matching against the registered account holder, since third-party payout is the pattern most closely associated with illegal flow. Document the reconciliation between reported gross gaming revenue and observed payment volume, because a divergence that the operator cannot explain will be explained for it."
 ]
},
{
 "slug": "us-state-igaming-tax-escalation-michigan-west-virginia-2026",
 "title": "US States Move to Raise iGaming Tax Rates",
 "category": "Tax",
 "excerpt": "Michigan and West Virginia proposals would lift online casino rates sharply. Operators face a repricing risk across every state.",
 "publish_date": "2026-09-22T09:00:00Z",
 "related_jurisdictions": ["united-states", "canada"],
 "related_firms": ["ifrah-law-pllc", "fox-rothschild-llp", "duane-morris-llp", "greenberg-traurig-llp", "dickinson-wright-pllc"],
 "body": [
  "A pattern that United States operators have watched develop in Europe is now visible domestically. Michigan's executive budget for the 2026-27 fiscal year proposed lifting the top marginal iGaming rate applied to online casino operators from twenty-eight percent to thirty-six percent for companies reporting more than one hundred and eighty-five million dollars in adjusted gross receipts, with the administration estimating between one hundred and seventy-five and one hundred and ninety-five million dollars in additional annual revenue. West Virginia measures have separately proposed raising the online casino rate from fifteen to twenty-five percent and the sports betting rate from ten to twenty-five percent. Neither proposal is isolated, and both reflect the same underlying arithmetic.",
  "That arithmetic is the consequence of iGaming's maturation as a revenue source. Annual iGaming revenue exceeded that of commercial land-based casinos in both Pennsylvania and New Jersey for the first time in 2025, which converts online casino taxation from a marginal line item into a material component of state revenue. Once a tax base is large enough to close a budget gap, it becomes a candidate for adjustment in every legislative session, and the political economy of gambling taxation offers unusually little resistance. There is no constituency of taxpayers who will campaign against a rate increase that falls on operators, and the revenue is scored immediately.",
  "Operators have generally underweighted this risk in their financial models, and counsel at Ifrah Law PLLC, Fox Rothschild LLP, Duane Morris LLP, Greenberg Traurig LLP and Dickinson Wright PLLC have been raising it in the context of licence renewals, acquisitions and market entry decisions. The habitual assumption in United States market modelling has been that a state's tax rate is a fixed input established at legalisation. The European experience suggests otherwise. The Netherlands moved to 37.8 percent, Sweden to twenty-two percent, and multiple jurisdictions have adjusted more than once. A model that treats the current rate as durable is not conservative; it is simply incomplete.",
  "The graduated structure of the Michigan proposal deserves particular attention because of its second-order effects. A rate that escalates above a revenue threshold creates a marginal disincentive at the threshold and, more importantly, alters the relative economics of scale. An operator approaching the threshold faces a materially different effective rate on incremental revenue than a smaller competitor does, which compresses the return on marketing spend at exactly the point where market leadership is being contested. Whether that effect is intended is uncertain; that it is real is not, and it should feature in any competitive response analysis.",
  "The channelisation question that dominates European tax debate arrives in the United States in a different form and is frequently misstated in the domestic discussion. In Europe, the alternative to a licensed operator is an offshore one, and the argument is that higher tax reduces the licensed product's competitiveness against it. In the United States, the alternative supply includes offshore sites, unregulated sweepstakes-model products and, increasingly, federally regulated event contracts offering functionally comparable exposure at a different tax treatment. A state raising its iGaming rate without addressing those adjacent channels may transfer activity rather than revenue, and the modelling required to test that proposition is not generally being performed before enactment.",
  "There is a contractual dimension that operators should examine before the next legislative cycle rather than after it. Revenue share agreements with platform providers, content suppliers and market access partners are commonly struck as a percentage of net gaming revenue, with the definition of net revenue determining who absorbs a tax increase. Where the definition is silent or ambiguous, a rate rise can fall entirely on one party in a way neither intended when the agreement was signed. Market access agreements with tribal or commercial licence holders present the same issue with greater rigidity, because the fee is frequently fixed and therefore unresponsive to margin compression.",
  "For operators active in both United States and Canadian markets, the comparison is instructive rather than reassuring. Ontario's model, built around a regulated operating agreement with a twenty percent share of gross gaming revenue, and Alberta's newly opened market have offered relative stability, but the structural pressures are the same and the Canadian provinces are watching the same revenue lines. Operators should not assume that a provincial rate set at market opening is any more permanent than a state rate set at legalisation, and should build renegotiation scenarios into multi-year plans in both countries.",
  "The practical response is not advocacy alone, though industry engagement in the legislative process retains value where it supplies evidence rather than assertion. It is scenario modelling that treats the tax rate as a variable, contractual review that allocates the risk of change explicitly, and portfolio construction that avoids concentration in any single state whose fiscal position makes an increase probable. Operators that can demonstrate to a legislature what a proposed rate does to licensed market share, with data rather than with warnings, will be heard more attentively than those that arrive with a projection of harm and no measurement behind it."
 ]
},
{
 "slug": "germany-ggl-2027-licensing-cycle-treaty-evaluation-market-entry-2026",
 "title": "Germany's 2027 Licence Cycle Opens a Narrow Door",
 "category": "Market Entry",
 "excerpt": "The State Treaty evaluation and a new licensing cycle from 2027 give entrants a rare window into the German market.",
 "publish_date": "2026-09-22T09:45:00Z",
 "related_jurisdictions": ["germany", "austria", "switzerland"],
 "related_firms": ["hambach-and-hambach", "redeker-sellner-dahs", "cms-germany", "bird-and-bird"],
 "body": [
  "The Gemeinsame Glücksspielbehörde der Länder has framed 2026 as a pivotal year, with the statutory evaluation of the 2021 State Treaty on Gambling under way and a new licensing cycle commencing in 2027. For operators outside the German market, and for licensed operators whose current permissions approach their term, those two processes together constitute the most significant German market entry opportunity since the treaty took effect. They also constitute a test that a meaningful number of current participants are unlikely to pass unchanged, which is the feature entrants should be studying most closely.",
  "The German regime's defining characteristics are the ones that have made it commercially difficult and legally distinctive: a one euro stake limit on virtual slot machines, a one thousand euro cross-operator monthly deposit ceiling administered through a central file, mandatory activity registration through the LUGAS system, and a five-minute mandatory break between different gambling forms. Each of these was adopted as a player protection measure and each has been cited in the channelisation debate as a reason customers remain with unlicensed supply. The evaluation is the formal mechanism through which those choices are reconsidered, and it is the reason the 2027 cycle may not simply renew the 2021 settlement.",
  "Channelisation figures are the evidence that will shape the outcome and they are contested in both directions. The GGL has reported a regulated market share in the region of seventy-seven percent measured across the gambling market as a whole, while industry analyses focusing specifically on online casino products place the figure substantially lower. The discrepancy is not primarily a dispute about data quality; it is a dispute about denominators, and which denominator the evaluation adopts will largely determine whether the existing restrictions are read as successful or as counterproductive. Entrants should understand that the regulatory direction of the next cycle turns on a methodological question as much as on a policy one.",
  "For a prospective applicant, the preparation required is more demanding than in most European jurisdictions and begins well before any application. German licensing requires demonstrable technical integration with the central systems, a safe server located within the jurisdiction or an approved equivalent, documented reliability of the applicant and its beneficial owners, and evidence that the applicant has not conducted unlicensed activity directed at German consumers. That last point disqualifies more applicants than any other. Counsel at Hambach & Hambach, Redeker Sellner Dahs, CMS Germany and Bird & Bird have consistently advised that prior German-facing activity without a licence is a fact pattern the authority investigates rather than assumes away.",
  "The civil litigation overhang is a distinct diligence item that acquirers and entrants must price. German courts have entertained large volumes of player recovery claims seeking repayment of losses incurred with operators that lacked German authorisation at the relevant time, and the exposure attaches to the entity that took the stakes. An entrant acquiring a German-facing business, or acquiring a group with historic German-facing activity, is acquiring that contingent liability unless the transaction structure excludes it effectively. Hive-down and asset acquisition structures are commonly used to address this, and equally commonly fail to address it where the regulator or a court looks to economic continuity rather than corporate form.",
  "The adjacent markets sharpen the strategic calculation. Austria's monopoly model has been under sustained pressure from European law arguments and from a domestic reform debate, and Switzerland's closed model, which confines online supply to holders of land-based casino concessions, is itself subject to an evaluation of the Money Gaming Act. An operator building German-compliant infrastructure, particularly around deposit ceilings, activity registration and cross-operator limit checking, is building capability that transfers directly if either neighbouring market opens. The German build should therefore be assessed as a regional platform investment rather than as a single-market cost.",
  "There is a timing judgement that entrants must make deliberately. Applying under the current framework means accepting the existing restrictions with no assurance they will be relaxed, and committing capital to a build specified against rules that may change. Waiting for the evaluation's output means arriving after incumbents have entrenched and after the 2027 cycle has allocated attention and supervisory capacity. The middle course, which the better-advised applicants are taking, is to complete the work that is invariant to the evaluation, being corporate structure, beneficial ownership documentation, anti-money laundering framework and technical integration design, while deferring only the product configuration decisions that the evaluation could genuinely alter.",
  "Operators already licensed in Germany should not read the new cycle as an administrative renewal. A licensing cycle that follows a statutory evaluation is an occasion on which the authority reassesses participants against a record it has now accumulated over several years, including LUGAS data, complaint history, advertising compliance and any enforcement correspondence. Licensees whose supervisory file contains unresolved items should resolve them before the cycle opens rather than explaining them during it, because the reassessment will proceed from what the authority already holds rather than from what the licensee chooses to present."
 ]
},
{
 "slug": "licence-surrender-during-regulatory-review-fitness-consequences-2026",
 "title": "Surrendering a Licence Does Not End the Review",
 "category": "Enforcement",
 "excerpt": "Two British operators handed back licences days after suspension. Exit closes the file in one jurisdiction and opens it elsewhere.",
 "publish_date": "2026-09-22T10:30:00Z",
 "related_jurisdictions": ["united-kingdom", "malta", "isle-of-man"],
 "related_firms": ["harris-hagan", "northridge-law-llp", "camilleri-preziosi", "wh-partners", "cains"],
 "body": [
  "The Gambling Commission suspended the operating licences of BresBet Ltd and Bet St George Ltd with immediate effect at the end of August, having opened reviews under section 116 of the Gambling Act 2005 on suspicion of social responsibility and anti-money laundering failings, and both companies surrendered their licences within days rather than continue under suspension. One of the two had entered the British market only months earlier. The episode is worth examining not for the underlying conduct, which has not been adjudicated, but for what the sequence reveals about the strategic position of an operator facing a review it does not expect to survive.",
  "Section 116 gives the Commission power to review a licence where it suspects that the holder may be unsuitable or may have failed to comply with conditions, and section 118 permits suspension pending that review. Suspension is not a sanction and does not require a finding; it is a protective measure, and its practical effect is severe. A suspended operator may generally permit customers to access accounts and withdraw funds but cannot accept new business, which means the revenue stops while the cost base, the customer service obligation and the regulatory engagement all continue. For a business without deep reserves, the suspension itself is frequently the determinative event regardless of how the review would have concluded.",
  "That dynamic creates an incentive to surrender, and operators contemplating it should understand precisely what surrender does and does not achieve. It ends the licence and with it the Commission's jurisdiction to impose a sanction under that licence, which removes the prospect of a published financial penalty and a regulatory settlement notice. It does not erase the review, the suspicion that prompted it or the Commission's record of both, and it does not affect any parallel exposure, whether that is a police interest, a claim by customers, or the position of directors under other regimes. Counsel at Harris Hagan and Northridge Law LLP have repeatedly cautioned that surrender is a decision about the licence rather than a decision about the consequences.",
  "The consequence that operators most often underestimate is the effect on individuals. British licensing applies a fitness and propriety assessment to personal management licence holders and to persons exercising significant influence, and that assessment is not extinguished when the corporate licence ends. A director associated with an operator whose licence was suspended on suspicion of social responsibility and money laundering failings carries that association into any subsequent application, in Britain and elsewhere. The question on a licensing form is rarely whether a sanction was imposed; it is generally whether the applicant has been the subject of regulatory action, investigation or review, and a suspension answers that question affirmatively.",
  "The cross-jurisdictional read-across is where the practical consequences accumulate. The Malta Gaming Authority, the Isle of Man Gambling Supervision Commission and comparable authorities in Gibraltar and Alderney all conduct fitness and probity assessments that examine regulatory history in other jurisdictions, and all of them exchange information with British counterparts. Practitioners at Camilleri Preziosi, WH Partners and Cains advise clients that a British suspension will be known to those authorities whether or not it is disclosed, and that non-disclosure converts a manageable historical fact into a current integrity concern, which is a far more serious problem than the original matter.",
  "For the customers of a surrendering operator, the position is governed by the licence conditions that applied while the licence subsisted, principally the requirement to hold customer funds in a manner consistent with the disclosed protection rating and to inform customers of the level of protection. Where funds were held under the lowest rating, customers are unsecured creditors in any subsequent insolvency, a fact disclosed in terms that few customers read. A rapid market exit therefore tests whether the segregation arrangements described in the licence application were actually operated, and that is a question the Commission can pursue through other routes even after the licence ends.",
  "There is a market entry lesson in the fact that one of the two operators had held its licence for only months. Licensing is granted on the strength of an applicant's representations about systems it intends to operate, and the interval between grant and first substantive supervisory contact is the period in which the gap between representation and operation becomes visible. A new entrant that scales customer acquisition before its anti-money laundering and social responsibility controls have been tested at volume is constructing precisely the fact pattern that produces an early review. The sequencing error is common and it is expensive.",
  "For operators currently under review and considering their options, the analytical framework should be explicit rather than instinctive. Establish whether the business can fund the suspension period, because that constrains everything else. Establish what a completed review would most likely produce, since a remediation-based outcome that preserves the licence is frequently available where the failings are systemic rather than dishonest. Establish where the individuals involved intend to work next, because the individual consequences persist for years while the corporate ones end at surrender. An operator that runs those three questions deliberately will sometimes still surrender, but it will do so knowing what it has bought."
 ]
},
]


def esc(s):
    return json.dumps(s, ensure_ascii=False)


def build_entry(a):
    return (
        '    {slug:%s,title:%s,category:%s,excerpt:%s,'
        'author:"%s",author_slug:"",publish_date:%s,'
        'related_jurisdictions:%s,related_firms:%s,related_lawyers:[]},\n'
        % (
            esc(a["slug"]),
            esc(a["title"]),
            esc(a["category"]),
            esc(a["excerpt"]),
            AUTHOR,
            esc(a["publish_date"]),
            json.dumps(a["related_jurisdictions"], ensure_ascii=False),
            json.dumps(a["related_firms"], ensure_ascii=False),
        )
    )


def build_body(a):
    paras = ",".join(esc(p) for p in a["body"])
    return '  %s:[%s],\n' % (esc(a["slug"]), paras)


def patch(path):
    src = open(path, encoding="utf-8").read()
    orig_len = len(src)

    for a in ARTICLES:
        if '"%s"' % a["slug"] in src:
            sys.exit("slug already present in %s: %s" % (path, a["slug"]))

    m = re.search(r'\n  articles: \[\n', src)
    if not m:
        sys.exit("articles array not found in %s" % path)
    entries = "".join(build_entry(a) for a in ARTICLES)
    src = src[:m.end()] + entries + src[m.end():]

    m2 = re.search(r'ARTICLE_BODIES = \{\n', src)
    if not m2:
        sys.exit("ARTICLE_BODIES not found in %s" % path)
    bodies = "".join(build_body(a) for a in ARTICLES)
    src = src[:m2.end()] + bodies + src[m2.end():]

    open(path, "w", encoding="utf-8").write(src)
    print("patched %s (+%d bytes)" % (os.path.basename(path), len(src) - orig_len))


if __name__ == "__main__":
    for fn in ("_source.html", "app.js"):
        p = os.path.join(BASE, fn)
        shutil.copy2(p, p + ".pre_22sep.bak")
        patch(p)
    print("done")
